
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `BrandResponsible` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model BrandResponsible
 * 
 */
export type BrandResponsibleModel = runtime.Types.Result.DefaultSelection<Prisma.$BrandResponsiblePayload>

export type AggregateBrandResponsible = {
  _count: BrandResponsibleCountAggregateOutputType | null
  _min: BrandResponsibleMinAggregateOutputType | null
  _max: BrandResponsibleMaxAggregateOutputType | null
}

export type BrandResponsibleMinAggregateOutputType = {
  id: string | null
  role: string | null
  name: string | null
  createdAt: Date | null
  updatedAt: Date | null
  brandAddressId: string | null
}

export type BrandResponsibleMaxAggregateOutputType = {
  id: string | null
  role: string | null
  name: string | null
  createdAt: Date | null
  updatedAt: Date | null
  brandAddressId: string | null
}

export type BrandResponsibleCountAggregateOutputType = {
  id: number
  role: number
  name: number
  createdAt: number
  updatedAt: number
  brandAddressId: number
  _all: number
}


export type BrandResponsibleMinAggregateInputType = {
  id?: true
  role?: true
  name?: true
  createdAt?: true
  updatedAt?: true
  brandAddressId?: true
}

export type BrandResponsibleMaxAggregateInputType = {
  id?: true
  role?: true
  name?: true
  createdAt?: true
  updatedAt?: true
  brandAddressId?: true
}

export type BrandResponsibleCountAggregateInputType = {
  id?: true
  role?: true
  name?: true
  createdAt?: true
  updatedAt?: true
  brandAddressId?: true
  _all?: true
}

export type BrandResponsibleAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which BrandResponsible to aggregate.
   */
  where?: Prisma.BrandResponsibleWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BrandResponsibles to fetch.
   */
  orderBy?: Prisma.BrandResponsibleOrderByWithRelationInput | Prisma.BrandResponsibleOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.BrandResponsibleWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BrandResponsibles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BrandResponsibles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned BrandResponsibles
  **/
  _count?: true | BrandResponsibleCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: BrandResponsibleMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: BrandResponsibleMaxAggregateInputType
}

export type GetBrandResponsibleAggregateType<T extends BrandResponsibleAggregateArgs> = {
      [P in keyof T & keyof AggregateBrandResponsible]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateBrandResponsible[P]>
    : Prisma.GetScalarType<T[P], AggregateBrandResponsible[P]>
}




export type BrandResponsibleGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.BrandResponsibleWhereInput
  orderBy?: Prisma.BrandResponsibleOrderByWithAggregationInput | Prisma.BrandResponsibleOrderByWithAggregationInput[]
  by: Prisma.BrandResponsibleScalarFieldEnum[] | Prisma.BrandResponsibleScalarFieldEnum
  having?: Prisma.BrandResponsibleScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: BrandResponsibleCountAggregateInputType | true
  _min?: BrandResponsibleMinAggregateInputType
  _max?: BrandResponsibleMaxAggregateInputType
}

export type BrandResponsibleGroupByOutputType = {
  id: string
  role: string | null
  name: string
  createdAt: Date
  updatedAt: Date
  brandAddressId: string
  _count: BrandResponsibleCountAggregateOutputType | null
  _min: BrandResponsibleMinAggregateOutputType | null
  _max: BrandResponsibleMaxAggregateOutputType | null
}

export type GetBrandResponsibleGroupByPayload<T extends BrandResponsibleGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<BrandResponsibleGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof BrandResponsibleGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], BrandResponsibleGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], BrandResponsibleGroupByOutputType[P]>
      }
    >
  >



export type BrandResponsibleWhereInput = {
  AND?: Prisma.BrandResponsibleWhereInput | Prisma.BrandResponsibleWhereInput[]
  OR?: Prisma.BrandResponsibleWhereInput[]
  NOT?: Prisma.BrandResponsibleWhereInput | Prisma.BrandResponsibleWhereInput[]
  id?: Prisma.StringFilter<"BrandResponsible"> | string
  role?: Prisma.StringNullableFilter<"BrandResponsible"> | string | null
  name?: Prisma.StringFilter<"BrandResponsible"> | string
  createdAt?: Prisma.DateTimeFilter<"BrandResponsible"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"BrandResponsible"> | Date | string
  brandAddressId?: Prisma.StringFilter<"BrandResponsible"> | string
  brandAddress?: Prisma.XOR<Prisma.BrandAddressScalarRelationFilter, Prisma.BrandAddressWhereInput>
}

export type BrandResponsibleOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  role?: Prisma.SortOrderInput | Prisma.SortOrder
  name?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  brandAddressId?: Prisma.SortOrder
  brandAddress?: Prisma.BrandAddressOrderByWithRelationInput
}

export type BrandResponsibleWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.BrandResponsibleWhereInput | Prisma.BrandResponsibleWhereInput[]
  OR?: Prisma.BrandResponsibleWhereInput[]
  NOT?: Prisma.BrandResponsibleWhereInput | Prisma.BrandResponsibleWhereInput[]
  role?: Prisma.StringNullableFilter<"BrandResponsible"> | string | null
  name?: Prisma.StringFilter<"BrandResponsible"> | string
  createdAt?: Prisma.DateTimeFilter<"BrandResponsible"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"BrandResponsible"> | Date | string
  brandAddressId?: Prisma.StringFilter<"BrandResponsible"> | string
  brandAddress?: Prisma.XOR<Prisma.BrandAddressScalarRelationFilter, Prisma.BrandAddressWhereInput>
}, "id">

export type BrandResponsibleOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  role?: Prisma.SortOrderInput | Prisma.SortOrder
  name?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  brandAddressId?: Prisma.SortOrder
  _count?: Prisma.BrandResponsibleCountOrderByAggregateInput
  _max?: Prisma.BrandResponsibleMaxOrderByAggregateInput
  _min?: Prisma.BrandResponsibleMinOrderByAggregateInput
}

export type BrandResponsibleScalarWhereWithAggregatesInput = {
  AND?: Prisma.BrandResponsibleScalarWhereWithAggregatesInput | Prisma.BrandResponsibleScalarWhereWithAggregatesInput[]
  OR?: Prisma.BrandResponsibleScalarWhereWithAggregatesInput[]
  NOT?: Prisma.BrandResponsibleScalarWhereWithAggregatesInput | Prisma.BrandResponsibleScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"BrandResponsible"> | string
  role?: Prisma.StringNullableWithAggregatesFilter<"BrandResponsible"> | string | null
  name?: Prisma.StringWithAggregatesFilter<"BrandResponsible"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"BrandResponsible"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"BrandResponsible"> | Date | string
  brandAddressId?: Prisma.StringWithAggregatesFilter<"BrandResponsible"> | string
}

export type BrandResponsibleCreateInput = {
  id?: string
  role?: string | null
  name: string
  createdAt?: Date | string
  updatedAt?: Date | string
  brandAddress: Prisma.BrandAddressCreateNestedOneWithoutResponsiblesInput
}

export type BrandResponsibleUncheckedCreateInput = {
  id?: string
  role?: string | null
  name: string
  createdAt?: Date | string
  updatedAt?: Date | string
  brandAddressId: string
}

export type BrandResponsibleUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  brandAddress?: Prisma.BrandAddressUpdateOneRequiredWithoutResponsiblesNestedInput
}

export type BrandResponsibleUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  brandAddressId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type BrandResponsibleCreateManyInput = {
  id?: string
  role?: string | null
  name: string
  createdAt?: Date | string
  updatedAt?: Date | string
  brandAddressId: string
}

export type BrandResponsibleUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type BrandResponsibleUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  brandAddressId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type BrandResponsibleListRelationFilter = {
  every?: Prisma.BrandResponsibleWhereInput
  some?: Prisma.BrandResponsibleWhereInput
  none?: Prisma.BrandResponsibleWhereInput
}

export type BrandResponsibleOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type BrandResponsibleCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  role?: Prisma.SortOrder
  name?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  brandAddressId?: Prisma.SortOrder
}

export type BrandResponsibleMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  role?: Prisma.SortOrder
  name?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  brandAddressId?: Prisma.SortOrder
}

export type BrandResponsibleMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  role?: Prisma.SortOrder
  name?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  brandAddressId?: Prisma.SortOrder
}

export type BrandResponsibleCreateNestedManyWithoutBrandAddressInput = {
  create?: Prisma.XOR<Prisma.BrandResponsibleCreateWithoutBrandAddressInput, Prisma.BrandResponsibleUncheckedCreateWithoutBrandAddressInput> | Prisma.BrandResponsibleCreateWithoutBrandAddressInput[] | Prisma.BrandResponsibleUncheckedCreateWithoutBrandAddressInput[]
  connectOrCreate?: Prisma.BrandResponsibleCreateOrConnectWithoutBrandAddressInput | Prisma.BrandResponsibleCreateOrConnectWithoutBrandAddressInput[]
  createMany?: Prisma.BrandResponsibleCreateManyBrandAddressInputEnvelope
  connect?: Prisma.BrandResponsibleWhereUniqueInput | Prisma.BrandResponsibleWhereUniqueInput[]
}

export type BrandResponsibleUncheckedCreateNestedManyWithoutBrandAddressInput = {
  create?: Prisma.XOR<Prisma.BrandResponsibleCreateWithoutBrandAddressInput, Prisma.BrandResponsibleUncheckedCreateWithoutBrandAddressInput> | Prisma.BrandResponsibleCreateWithoutBrandAddressInput[] | Prisma.BrandResponsibleUncheckedCreateWithoutBrandAddressInput[]
  connectOrCreate?: Prisma.BrandResponsibleCreateOrConnectWithoutBrandAddressInput | Prisma.BrandResponsibleCreateOrConnectWithoutBrandAddressInput[]
  createMany?: Prisma.BrandResponsibleCreateManyBrandAddressInputEnvelope
  connect?: Prisma.BrandResponsibleWhereUniqueInput | Prisma.BrandResponsibleWhereUniqueInput[]
}

export type BrandResponsibleUpdateManyWithoutBrandAddressNestedInput = {
  create?: Prisma.XOR<Prisma.BrandResponsibleCreateWithoutBrandAddressInput, Prisma.BrandResponsibleUncheckedCreateWithoutBrandAddressInput> | Prisma.BrandResponsibleCreateWithoutBrandAddressInput[] | Prisma.BrandResponsibleUncheckedCreateWithoutBrandAddressInput[]
  connectOrCreate?: Prisma.BrandResponsibleCreateOrConnectWithoutBrandAddressInput | Prisma.BrandResponsibleCreateOrConnectWithoutBrandAddressInput[]
  upsert?: Prisma.BrandResponsibleUpsertWithWhereUniqueWithoutBrandAddressInput | Prisma.BrandResponsibleUpsertWithWhereUniqueWithoutBrandAddressInput[]
  createMany?: Prisma.BrandResponsibleCreateManyBrandAddressInputEnvelope
  set?: Prisma.BrandResponsibleWhereUniqueInput | Prisma.BrandResponsibleWhereUniqueInput[]
  disconnect?: Prisma.BrandResponsibleWhereUniqueInput | Prisma.BrandResponsibleWhereUniqueInput[]
  delete?: Prisma.BrandResponsibleWhereUniqueInput | Prisma.BrandResponsibleWhereUniqueInput[]
  connect?: Prisma.BrandResponsibleWhereUniqueInput | Prisma.BrandResponsibleWhereUniqueInput[]
  update?: Prisma.BrandResponsibleUpdateWithWhereUniqueWithoutBrandAddressInput | Prisma.BrandResponsibleUpdateWithWhereUniqueWithoutBrandAddressInput[]
  updateMany?: Prisma.BrandResponsibleUpdateManyWithWhereWithoutBrandAddressInput | Prisma.BrandResponsibleUpdateManyWithWhereWithoutBrandAddressInput[]
  deleteMany?: Prisma.BrandResponsibleScalarWhereInput | Prisma.BrandResponsibleScalarWhereInput[]
}

export type BrandResponsibleUncheckedUpdateManyWithoutBrandAddressNestedInput = {
  create?: Prisma.XOR<Prisma.BrandResponsibleCreateWithoutBrandAddressInput, Prisma.BrandResponsibleUncheckedCreateWithoutBrandAddressInput> | Prisma.BrandResponsibleCreateWithoutBrandAddressInput[] | Prisma.BrandResponsibleUncheckedCreateWithoutBrandAddressInput[]
  connectOrCreate?: Prisma.BrandResponsibleCreateOrConnectWithoutBrandAddressInput | Prisma.BrandResponsibleCreateOrConnectWithoutBrandAddressInput[]
  upsert?: Prisma.BrandResponsibleUpsertWithWhereUniqueWithoutBrandAddressInput | Prisma.BrandResponsibleUpsertWithWhereUniqueWithoutBrandAddressInput[]
  createMany?: Prisma.BrandResponsibleCreateManyBrandAddressInputEnvelope
  set?: Prisma.BrandResponsibleWhereUniqueInput | Prisma.BrandResponsibleWhereUniqueInput[]
  disconnect?: Prisma.BrandResponsibleWhereUniqueInput | Prisma.BrandResponsibleWhereUniqueInput[]
  delete?: Prisma.BrandResponsibleWhereUniqueInput | Prisma.BrandResponsibleWhereUniqueInput[]
  connect?: Prisma.BrandResponsibleWhereUniqueInput | Prisma.BrandResponsibleWhereUniqueInput[]
  update?: Prisma.BrandResponsibleUpdateWithWhereUniqueWithoutBrandAddressInput | Prisma.BrandResponsibleUpdateWithWhereUniqueWithoutBrandAddressInput[]
  updateMany?: Prisma.BrandResponsibleUpdateManyWithWhereWithoutBrandAddressInput | Prisma.BrandResponsibleUpdateManyWithWhereWithoutBrandAddressInput[]
  deleteMany?: Prisma.BrandResponsibleScalarWhereInput | Prisma.BrandResponsibleScalarWhereInput[]
}

export type BrandResponsibleCreateWithoutBrandAddressInput = {
  id?: string
  role?: string | null
  name: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type BrandResponsibleUncheckedCreateWithoutBrandAddressInput = {
  id?: string
  role?: string | null
  name: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type BrandResponsibleCreateOrConnectWithoutBrandAddressInput = {
  where: Prisma.BrandResponsibleWhereUniqueInput
  create: Prisma.XOR<Prisma.BrandResponsibleCreateWithoutBrandAddressInput, Prisma.BrandResponsibleUncheckedCreateWithoutBrandAddressInput>
}

export type BrandResponsibleCreateManyBrandAddressInputEnvelope = {
  data: Prisma.BrandResponsibleCreateManyBrandAddressInput | Prisma.BrandResponsibleCreateManyBrandAddressInput[]
  skipDuplicates?: boolean
}

export type BrandResponsibleUpsertWithWhereUniqueWithoutBrandAddressInput = {
  where: Prisma.BrandResponsibleWhereUniqueInput
  update: Prisma.XOR<Prisma.BrandResponsibleUpdateWithoutBrandAddressInput, Prisma.BrandResponsibleUncheckedUpdateWithoutBrandAddressInput>
  create: Prisma.XOR<Prisma.BrandResponsibleCreateWithoutBrandAddressInput, Prisma.BrandResponsibleUncheckedCreateWithoutBrandAddressInput>
}

export type BrandResponsibleUpdateWithWhereUniqueWithoutBrandAddressInput = {
  where: Prisma.BrandResponsibleWhereUniqueInput
  data: Prisma.XOR<Prisma.BrandResponsibleUpdateWithoutBrandAddressInput, Prisma.BrandResponsibleUncheckedUpdateWithoutBrandAddressInput>
}

export type BrandResponsibleUpdateManyWithWhereWithoutBrandAddressInput = {
  where: Prisma.BrandResponsibleScalarWhereInput
  data: Prisma.XOR<Prisma.BrandResponsibleUpdateManyMutationInput, Prisma.BrandResponsibleUncheckedUpdateManyWithoutBrandAddressInput>
}

export type BrandResponsibleScalarWhereInput = {
  AND?: Prisma.BrandResponsibleScalarWhereInput | Prisma.BrandResponsibleScalarWhereInput[]
  OR?: Prisma.BrandResponsibleScalarWhereInput[]
  NOT?: Prisma.BrandResponsibleScalarWhereInput | Prisma.BrandResponsibleScalarWhereInput[]
  id?: Prisma.StringFilter<"BrandResponsible"> | string
  role?: Prisma.StringNullableFilter<"BrandResponsible"> | string | null
  name?: Prisma.StringFilter<"BrandResponsible"> | string
  createdAt?: Prisma.DateTimeFilter<"BrandResponsible"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"BrandResponsible"> | Date | string
  brandAddressId?: Prisma.StringFilter<"BrandResponsible"> | string
}

export type BrandResponsibleCreateManyBrandAddressInput = {
  id?: string
  role?: string | null
  name: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type BrandResponsibleUpdateWithoutBrandAddressInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type BrandResponsibleUncheckedUpdateWithoutBrandAddressInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type BrandResponsibleUncheckedUpdateManyWithoutBrandAddressInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type BrandResponsibleSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  role?: boolean
  name?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  brandAddressId?: boolean
  brandAddress?: boolean | Prisma.BrandAddressDefaultArgs<ExtArgs>
}, ExtArgs["result"]["brandResponsible"]>

export type BrandResponsibleSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  role?: boolean
  name?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  brandAddressId?: boolean
  brandAddress?: boolean | Prisma.BrandAddressDefaultArgs<ExtArgs>
}, ExtArgs["result"]["brandResponsible"]>

export type BrandResponsibleSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  role?: boolean
  name?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  brandAddressId?: boolean
  brandAddress?: boolean | Prisma.BrandAddressDefaultArgs<ExtArgs>
}, ExtArgs["result"]["brandResponsible"]>

export type BrandResponsibleSelectScalar = {
  id?: boolean
  role?: boolean
  name?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  brandAddressId?: boolean
}

export type BrandResponsibleOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "role" | "name" | "createdAt" | "updatedAt" | "brandAddressId", ExtArgs["result"]["brandResponsible"]>
export type BrandResponsibleInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  brandAddress?: boolean | Prisma.BrandAddressDefaultArgs<ExtArgs>
}
export type BrandResponsibleIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  brandAddress?: boolean | Prisma.BrandAddressDefaultArgs<ExtArgs>
}
export type BrandResponsibleIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  brandAddress?: boolean | Prisma.BrandAddressDefaultArgs<ExtArgs>
}

export type $BrandResponsiblePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "BrandResponsible"
  objects: {
    brandAddress: Prisma.$BrandAddressPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    role: string | null
    name: string
    createdAt: Date
    updatedAt: Date
    brandAddressId: string
  }, ExtArgs["result"]["brandResponsible"]>
  composites: {}
}

export type BrandResponsibleGetPayload<S extends boolean | null | undefined | BrandResponsibleDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$BrandResponsiblePayload, S>

export type BrandResponsibleCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<BrandResponsibleFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: BrandResponsibleCountAggregateInputType | true
  }

export interface BrandResponsibleDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['BrandResponsible'], meta: { name: 'BrandResponsible' } }
  /**
   * Find zero or one BrandResponsible that matches the filter.
   * @param {BrandResponsibleFindUniqueArgs} args - Arguments to find a BrandResponsible
   * @example
   * // Get one BrandResponsible
   * const brandResponsible = await prisma.brandResponsible.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends BrandResponsibleFindUniqueArgs>(args: Prisma.SelectSubset<T, BrandResponsibleFindUniqueArgs<ExtArgs>>): Prisma.Prisma__BrandResponsibleClient<runtime.Types.Result.GetResult<Prisma.$BrandResponsiblePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one BrandResponsible that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {BrandResponsibleFindUniqueOrThrowArgs} args - Arguments to find a BrandResponsible
   * @example
   * // Get one BrandResponsible
   * const brandResponsible = await prisma.brandResponsible.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends BrandResponsibleFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, BrandResponsibleFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__BrandResponsibleClient<runtime.Types.Result.GetResult<Prisma.$BrandResponsiblePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first BrandResponsible that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BrandResponsibleFindFirstArgs} args - Arguments to find a BrandResponsible
   * @example
   * // Get one BrandResponsible
   * const brandResponsible = await prisma.brandResponsible.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends BrandResponsibleFindFirstArgs>(args?: Prisma.SelectSubset<T, BrandResponsibleFindFirstArgs<ExtArgs>>): Prisma.Prisma__BrandResponsibleClient<runtime.Types.Result.GetResult<Prisma.$BrandResponsiblePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first BrandResponsible that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BrandResponsibleFindFirstOrThrowArgs} args - Arguments to find a BrandResponsible
   * @example
   * // Get one BrandResponsible
   * const brandResponsible = await prisma.brandResponsible.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends BrandResponsibleFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, BrandResponsibleFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__BrandResponsibleClient<runtime.Types.Result.GetResult<Prisma.$BrandResponsiblePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more BrandResponsibles that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BrandResponsibleFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all BrandResponsibles
   * const brandResponsibles = await prisma.brandResponsible.findMany()
   * 
   * // Get first 10 BrandResponsibles
   * const brandResponsibles = await prisma.brandResponsible.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const brandResponsibleWithIdOnly = await prisma.brandResponsible.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends BrandResponsibleFindManyArgs>(args?: Prisma.SelectSubset<T, BrandResponsibleFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BrandResponsiblePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a BrandResponsible.
   * @param {BrandResponsibleCreateArgs} args - Arguments to create a BrandResponsible.
   * @example
   * // Create one BrandResponsible
   * const BrandResponsible = await prisma.brandResponsible.create({
   *   data: {
   *     // ... data to create a BrandResponsible
   *   }
   * })
   * 
   */
  create<T extends BrandResponsibleCreateArgs>(args: Prisma.SelectSubset<T, BrandResponsibleCreateArgs<ExtArgs>>): Prisma.Prisma__BrandResponsibleClient<runtime.Types.Result.GetResult<Prisma.$BrandResponsiblePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many BrandResponsibles.
   * @param {BrandResponsibleCreateManyArgs} args - Arguments to create many BrandResponsibles.
   * @example
   * // Create many BrandResponsibles
   * const brandResponsible = await prisma.brandResponsible.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends BrandResponsibleCreateManyArgs>(args?: Prisma.SelectSubset<T, BrandResponsibleCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many BrandResponsibles and returns the data saved in the database.
   * @param {BrandResponsibleCreateManyAndReturnArgs} args - Arguments to create many BrandResponsibles.
   * @example
   * // Create many BrandResponsibles
   * const brandResponsible = await prisma.brandResponsible.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many BrandResponsibles and only return the `id`
   * const brandResponsibleWithIdOnly = await prisma.brandResponsible.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends BrandResponsibleCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, BrandResponsibleCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BrandResponsiblePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a BrandResponsible.
   * @param {BrandResponsibleDeleteArgs} args - Arguments to delete one BrandResponsible.
   * @example
   * // Delete one BrandResponsible
   * const BrandResponsible = await prisma.brandResponsible.delete({
   *   where: {
   *     // ... filter to delete one BrandResponsible
   *   }
   * })
   * 
   */
  delete<T extends BrandResponsibleDeleteArgs>(args: Prisma.SelectSubset<T, BrandResponsibleDeleteArgs<ExtArgs>>): Prisma.Prisma__BrandResponsibleClient<runtime.Types.Result.GetResult<Prisma.$BrandResponsiblePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one BrandResponsible.
   * @param {BrandResponsibleUpdateArgs} args - Arguments to update one BrandResponsible.
   * @example
   * // Update one BrandResponsible
   * const brandResponsible = await prisma.brandResponsible.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends BrandResponsibleUpdateArgs>(args: Prisma.SelectSubset<T, BrandResponsibleUpdateArgs<ExtArgs>>): Prisma.Prisma__BrandResponsibleClient<runtime.Types.Result.GetResult<Prisma.$BrandResponsiblePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more BrandResponsibles.
   * @param {BrandResponsibleDeleteManyArgs} args - Arguments to filter BrandResponsibles to delete.
   * @example
   * // Delete a few BrandResponsibles
   * const { count } = await prisma.brandResponsible.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends BrandResponsibleDeleteManyArgs>(args?: Prisma.SelectSubset<T, BrandResponsibleDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more BrandResponsibles.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BrandResponsibleUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many BrandResponsibles
   * const brandResponsible = await prisma.brandResponsible.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends BrandResponsibleUpdateManyArgs>(args: Prisma.SelectSubset<T, BrandResponsibleUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more BrandResponsibles and returns the data updated in the database.
   * @param {BrandResponsibleUpdateManyAndReturnArgs} args - Arguments to update many BrandResponsibles.
   * @example
   * // Update many BrandResponsibles
   * const brandResponsible = await prisma.brandResponsible.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more BrandResponsibles and only return the `id`
   * const brandResponsibleWithIdOnly = await prisma.brandResponsible.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends BrandResponsibleUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, BrandResponsibleUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BrandResponsiblePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one BrandResponsible.
   * @param {BrandResponsibleUpsertArgs} args - Arguments to update or create a BrandResponsible.
   * @example
   * // Update or create a BrandResponsible
   * const brandResponsible = await prisma.brandResponsible.upsert({
   *   create: {
   *     // ... data to create a BrandResponsible
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the BrandResponsible we want to update
   *   }
   * })
   */
  upsert<T extends BrandResponsibleUpsertArgs>(args: Prisma.SelectSubset<T, BrandResponsibleUpsertArgs<ExtArgs>>): Prisma.Prisma__BrandResponsibleClient<runtime.Types.Result.GetResult<Prisma.$BrandResponsiblePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of BrandResponsibles.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BrandResponsibleCountArgs} args - Arguments to filter BrandResponsibles to count.
   * @example
   * // Count the number of BrandResponsibles
   * const count = await prisma.brandResponsible.count({
   *   where: {
   *     // ... the filter for the BrandResponsibles we want to count
   *   }
   * })
  **/
  count<T extends BrandResponsibleCountArgs>(
    args?: Prisma.Subset<T, BrandResponsibleCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], BrandResponsibleCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a BrandResponsible.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BrandResponsibleAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends BrandResponsibleAggregateArgs>(args: Prisma.Subset<T, BrandResponsibleAggregateArgs>): Prisma.PrismaPromise<GetBrandResponsibleAggregateType<T>>

  /**
   * Group by BrandResponsible.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BrandResponsibleGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends BrandResponsibleGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: BrandResponsibleGroupByArgs['orderBy'] }
      : { orderBy?: BrandResponsibleGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, BrandResponsibleGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetBrandResponsibleGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the BrandResponsible model
 */
readonly fields: BrandResponsibleFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for BrandResponsible.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__BrandResponsibleClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  brandAddress<T extends Prisma.BrandAddressDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.BrandAddressDefaultArgs<ExtArgs>>): Prisma.Prisma__BrandAddressClient<runtime.Types.Result.GetResult<Prisma.$BrandAddressPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the BrandResponsible model
 */
export interface BrandResponsibleFieldRefs {
  readonly id: Prisma.FieldRef<"BrandResponsible", 'String'>
  readonly role: Prisma.FieldRef<"BrandResponsible", 'String'>
  readonly name: Prisma.FieldRef<"BrandResponsible", 'String'>
  readonly createdAt: Prisma.FieldRef<"BrandResponsible", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"BrandResponsible", 'DateTime'>
  readonly brandAddressId: Prisma.FieldRef<"BrandResponsible", 'String'>
}
    

// Custom InputTypes
/**
 * BrandResponsible findUnique
 */
export type BrandResponsibleFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BrandResponsible
   */
  select?: Prisma.BrandResponsibleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BrandResponsible
   */
  omit?: Prisma.BrandResponsibleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BrandResponsibleInclude<ExtArgs> | null
  /**
   * Filter, which BrandResponsible to fetch.
   */
  where: Prisma.BrandResponsibleWhereUniqueInput
}

/**
 * BrandResponsible findUniqueOrThrow
 */
export type BrandResponsibleFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BrandResponsible
   */
  select?: Prisma.BrandResponsibleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BrandResponsible
   */
  omit?: Prisma.BrandResponsibleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BrandResponsibleInclude<ExtArgs> | null
  /**
   * Filter, which BrandResponsible to fetch.
   */
  where: Prisma.BrandResponsibleWhereUniqueInput
}

/**
 * BrandResponsible findFirst
 */
export type BrandResponsibleFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BrandResponsible
   */
  select?: Prisma.BrandResponsibleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BrandResponsible
   */
  omit?: Prisma.BrandResponsibleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BrandResponsibleInclude<ExtArgs> | null
  /**
   * Filter, which BrandResponsible to fetch.
   */
  where?: Prisma.BrandResponsibleWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BrandResponsibles to fetch.
   */
  orderBy?: Prisma.BrandResponsibleOrderByWithRelationInput | Prisma.BrandResponsibleOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for BrandResponsibles.
   */
  cursor?: Prisma.BrandResponsibleWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BrandResponsibles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BrandResponsibles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of BrandResponsibles.
   */
  distinct?: Prisma.BrandResponsibleScalarFieldEnum | Prisma.BrandResponsibleScalarFieldEnum[]
}

/**
 * BrandResponsible findFirstOrThrow
 */
export type BrandResponsibleFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BrandResponsible
   */
  select?: Prisma.BrandResponsibleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BrandResponsible
   */
  omit?: Prisma.BrandResponsibleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BrandResponsibleInclude<ExtArgs> | null
  /**
   * Filter, which BrandResponsible to fetch.
   */
  where?: Prisma.BrandResponsibleWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BrandResponsibles to fetch.
   */
  orderBy?: Prisma.BrandResponsibleOrderByWithRelationInput | Prisma.BrandResponsibleOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for BrandResponsibles.
   */
  cursor?: Prisma.BrandResponsibleWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BrandResponsibles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BrandResponsibles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of BrandResponsibles.
   */
  distinct?: Prisma.BrandResponsibleScalarFieldEnum | Prisma.BrandResponsibleScalarFieldEnum[]
}

/**
 * BrandResponsible findMany
 */
export type BrandResponsibleFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BrandResponsible
   */
  select?: Prisma.BrandResponsibleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BrandResponsible
   */
  omit?: Prisma.BrandResponsibleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BrandResponsibleInclude<ExtArgs> | null
  /**
   * Filter, which BrandResponsibles to fetch.
   */
  where?: Prisma.BrandResponsibleWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BrandResponsibles to fetch.
   */
  orderBy?: Prisma.BrandResponsibleOrderByWithRelationInput | Prisma.BrandResponsibleOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing BrandResponsibles.
   */
  cursor?: Prisma.BrandResponsibleWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BrandResponsibles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BrandResponsibles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of BrandResponsibles.
   */
  distinct?: Prisma.BrandResponsibleScalarFieldEnum | Prisma.BrandResponsibleScalarFieldEnum[]
}

/**
 * BrandResponsible create
 */
export type BrandResponsibleCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BrandResponsible
   */
  select?: Prisma.BrandResponsibleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BrandResponsible
   */
  omit?: Prisma.BrandResponsibleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BrandResponsibleInclude<ExtArgs> | null
  /**
   * The data needed to create a BrandResponsible.
   */
  data: Prisma.XOR<Prisma.BrandResponsibleCreateInput, Prisma.BrandResponsibleUncheckedCreateInput>
}

/**
 * BrandResponsible createMany
 */
export type BrandResponsibleCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many BrandResponsibles.
   */
  data: Prisma.BrandResponsibleCreateManyInput | Prisma.BrandResponsibleCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * BrandResponsible createManyAndReturn
 */
export type BrandResponsibleCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BrandResponsible
   */
  select?: Prisma.BrandResponsibleSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the BrandResponsible
   */
  omit?: Prisma.BrandResponsibleOmit<ExtArgs> | null
  /**
   * The data used to create many BrandResponsibles.
   */
  data: Prisma.BrandResponsibleCreateManyInput | Prisma.BrandResponsibleCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BrandResponsibleIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * BrandResponsible update
 */
export type BrandResponsibleUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BrandResponsible
   */
  select?: Prisma.BrandResponsibleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BrandResponsible
   */
  omit?: Prisma.BrandResponsibleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BrandResponsibleInclude<ExtArgs> | null
  /**
   * The data needed to update a BrandResponsible.
   */
  data: Prisma.XOR<Prisma.BrandResponsibleUpdateInput, Prisma.BrandResponsibleUncheckedUpdateInput>
  /**
   * Choose, which BrandResponsible to update.
   */
  where: Prisma.BrandResponsibleWhereUniqueInput
}

/**
 * BrandResponsible updateMany
 */
export type BrandResponsibleUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update BrandResponsibles.
   */
  data: Prisma.XOR<Prisma.BrandResponsibleUpdateManyMutationInput, Prisma.BrandResponsibleUncheckedUpdateManyInput>
  /**
   * Filter which BrandResponsibles to update
   */
  where?: Prisma.BrandResponsibleWhereInput
  /**
   * Limit how many BrandResponsibles to update.
   */
  limit?: number
}

/**
 * BrandResponsible updateManyAndReturn
 */
export type BrandResponsibleUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BrandResponsible
   */
  select?: Prisma.BrandResponsibleSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the BrandResponsible
   */
  omit?: Prisma.BrandResponsibleOmit<ExtArgs> | null
  /**
   * The data used to update BrandResponsibles.
   */
  data: Prisma.XOR<Prisma.BrandResponsibleUpdateManyMutationInput, Prisma.BrandResponsibleUncheckedUpdateManyInput>
  /**
   * Filter which BrandResponsibles to update
   */
  where?: Prisma.BrandResponsibleWhereInput
  /**
   * Limit how many BrandResponsibles to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BrandResponsibleIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * BrandResponsible upsert
 */
export type BrandResponsibleUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BrandResponsible
   */
  select?: Prisma.BrandResponsibleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BrandResponsible
   */
  omit?: Prisma.BrandResponsibleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BrandResponsibleInclude<ExtArgs> | null
  /**
   * The filter to search for the BrandResponsible to update in case it exists.
   */
  where: Prisma.BrandResponsibleWhereUniqueInput
  /**
   * In case the BrandResponsible found by the `where` argument doesn't exist, create a new BrandResponsible with this data.
   */
  create: Prisma.XOR<Prisma.BrandResponsibleCreateInput, Prisma.BrandResponsibleUncheckedCreateInput>
  /**
   * In case the BrandResponsible was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.BrandResponsibleUpdateInput, Prisma.BrandResponsibleUncheckedUpdateInput>
}

/**
 * BrandResponsible delete
 */
export type BrandResponsibleDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BrandResponsible
   */
  select?: Prisma.BrandResponsibleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BrandResponsible
   */
  omit?: Prisma.BrandResponsibleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BrandResponsibleInclude<ExtArgs> | null
  /**
   * Filter which BrandResponsible to delete.
   */
  where: Prisma.BrandResponsibleWhereUniqueInput
}

/**
 * BrandResponsible deleteMany
 */
export type BrandResponsibleDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which BrandResponsibles to delete
   */
  where?: Prisma.BrandResponsibleWhereInput
  /**
   * Limit how many BrandResponsibles to delete.
   */
  limit?: number
}

/**
 * BrandResponsible without action
 */
export type BrandResponsibleDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BrandResponsible
   */
  select?: Prisma.BrandResponsibleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BrandResponsible
   */
  omit?: Prisma.BrandResponsibleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BrandResponsibleInclude<ExtArgs> | null
}
