
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Brand` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model Brand
 * 
 */
export type BrandModel = runtime.Types.Result.DefaultSelection<Prisma.$BrandPayload>

export type AggregateBrand = {
  _count: BrandCountAggregateOutputType | null
  _min: BrandMinAggregateOutputType | null
  _max: BrandMaxAggregateOutputType | null
}

export type BrandMinAggregateOutputType = {
  id: string | null
  name: string | null
  segment: $Enums.BusinessSegment | null
  responsible: string | null
  description: string | null
  logoUrl: string | null
  slogan: string | null
  phoneNumber: string | null
  whatsapp: string | null
  instagram: string | null
  tiktok: string | null
  facebook: string | null
  website: string | null
  createdAt: Date | null
  updatedAt: Date | null
  workspaceId: string | null
}

export type BrandMaxAggregateOutputType = {
  id: string | null
  name: string | null
  segment: $Enums.BusinessSegment | null
  responsible: string | null
  description: string | null
  logoUrl: string | null
  slogan: string | null
  phoneNumber: string | null
  whatsapp: string | null
  instagram: string | null
  tiktok: string | null
  facebook: string | null
  website: string | null
  createdAt: Date | null
  updatedAt: Date | null
  workspaceId: string | null
}

export type BrandCountAggregateOutputType = {
  id: number
  name: number
  segment: number
  responsible: number
  description: number
  logoUrl: number
  slogan: number
  phoneNumber: number
  whatsapp: number
  instagram: number
  tiktok: number
  facebook: number
  website: number
  createdAt: number
  updatedAt: number
  workspaceId: number
  _all: number
}


export type BrandMinAggregateInputType = {
  id?: true
  name?: true
  segment?: true
  responsible?: true
  description?: true
  logoUrl?: true
  slogan?: true
  phoneNumber?: true
  whatsapp?: true
  instagram?: true
  tiktok?: true
  facebook?: true
  website?: true
  createdAt?: true
  updatedAt?: true
  workspaceId?: true
}

export type BrandMaxAggregateInputType = {
  id?: true
  name?: true
  segment?: true
  responsible?: true
  description?: true
  logoUrl?: true
  slogan?: true
  phoneNumber?: true
  whatsapp?: true
  instagram?: true
  tiktok?: true
  facebook?: true
  website?: true
  createdAt?: true
  updatedAt?: true
  workspaceId?: true
}

export type BrandCountAggregateInputType = {
  id?: true
  name?: true
  segment?: true
  responsible?: true
  description?: true
  logoUrl?: true
  slogan?: true
  phoneNumber?: true
  whatsapp?: true
  instagram?: true
  tiktok?: true
  facebook?: true
  website?: true
  createdAt?: true
  updatedAt?: true
  workspaceId?: true
  _all?: true
}

export type BrandAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Brand to aggregate.
   */
  where?: Prisma.BrandWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Brands to fetch.
   */
  orderBy?: Prisma.BrandOrderByWithRelationInput | Prisma.BrandOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.BrandWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Brands from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Brands.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Brands
  **/
  _count?: true | BrandCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: BrandMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: BrandMaxAggregateInputType
}

export type GetBrandAggregateType<T extends BrandAggregateArgs> = {
      [P in keyof T & keyof AggregateBrand]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateBrand[P]>
    : Prisma.GetScalarType<T[P], AggregateBrand[P]>
}




export type BrandGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.BrandWhereInput
  orderBy?: Prisma.BrandOrderByWithAggregationInput | Prisma.BrandOrderByWithAggregationInput[]
  by: Prisma.BrandScalarFieldEnum[] | Prisma.BrandScalarFieldEnum
  having?: Prisma.BrandScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: BrandCountAggregateInputType | true
  _min?: BrandMinAggregateInputType
  _max?: BrandMaxAggregateInputType
}

export type BrandGroupByOutputType = {
  id: string
  name: string
  segment: $Enums.BusinessSegment
  responsible: string | null
  description: string | null
  logoUrl: string | null
  slogan: string | null
  phoneNumber: string | null
  whatsapp: string | null
  instagram: string | null
  tiktok: string | null
  facebook: string | null
  website: string | null
  createdAt: Date
  updatedAt: Date
  workspaceId: string
  _count: BrandCountAggregateOutputType | null
  _min: BrandMinAggregateOutputType | null
  _max: BrandMaxAggregateOutputType | null
}

export type GetBrandGroupByPayload<T extends BrandGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<BrandGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof BrandGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], BrandGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], BrandGroupByOutputType[P]>
      }
    >
  >



export type BrandWhereInput = {
  AND?: Prisma.BrandWhereInput | Prisma.BrandWhereInput[]
  OR?: Prisma.BrandWhereInput[]
  NOT?: Prisma.BrandWhereInput | Prisma.BrandWhereInput[]
  id?: Prisma.StringFilter<"Brand"> | string
  name?: Prisma.StringFilter<"Brand"> | string
  segment?: Prisma.EnumBusinessSegmentFilter<"Brand"> | $Enums.BusinessSegment
  responsible?: Prisma.StringNullableFilter<"Brand"> | string | null
  description?: Prisma.StringNullableFilter<"Brand"> | string | null
  logoUrl?: Prisma.StringNullableFilter<"Brand"> | string | null
  slogan?: Prisma.StringNullableFilter<"Brand"> | string | null
  phoneNumber?: Prisma.StringNullableFilter<"Brand"> | string | null
  whatsapp?: Prisma.StringNullableFilter<"Brand"> | string | null
  instagram?: Prisma.StringNullableFilter<"Brand"> | string | null
  tiktok?: Prisma.StringNullableFilter<"Brand"> | string | null
  facebook?: Prisma.StringNullableFilter<"Brand"> | string | null
  website?: Prisma.StringNullableFilter<"Brand"> | string | null
  createdAt?: Prisma.DateTimeFilter<"Brand"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Brand"> | Date | string
  workspaceId?: Prisma.StringFilter<"Brand"> | string
  workspace?: Prisma.XOR<Prisma.WorkspaceScalarRelationFilter, Prisma.WorkspaceWhereInput>
  spots?: Prisma.SpotListRelationFilter
  addresses?: Prisma.BrandAddressListRelationFilter
}

export type BrandOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  segment?: Prisma.SortOrder
  responsible?: Prisma.SortOrderInput | Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  logoUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  slogan?: Prisma.SortOrderInput | Prisma.SortOrder
  phoneNumber?: Prisma.SortOrderInput | Prisma.SortOrder
  whatsapp?: Prisma.SortOrderInput | Prisma.SortOrder
  instagram?: Prisma.SortOrderInput | Prisma.SortOrder
  tiktok?: Prisma.SortOrderInput | Prisma.SortOrder
  facebook?: Prisma.SortOrderInput | Prisma.SortOrder
  website?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  workspaceId?: Prisma.SortOrder
  workspace?: Prisma.WorkspaceOrderByWithRelationInput
  spots?: Prisma.SpotOrderByRelationAggregateInput
  addresses?: Prisma.BrandAddressOrderByRelationAggregateInput
}

export type BrandWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.BrandWhereInput | Prisma.BrandWhereInput[]
  OR?: Prisma.BrandWhereInput[]
  NOT?: Prisma.BrandWhereInput | Prisma.BrandWhereInput[]
  name?: Prisma.StringFilter<"Brand"> | string
  segment?: Prisma.EnumBusinessSegmentFilter<"Brand"> | $Enums.BusinessSegment
  responsible?: Prisma.StringNullableFilter<"Brand"> | string | null
  description?: Prisma.StringNullableFilter<"Brand"> | string | null
  logoUrl?: Prisma.StringNullableFilter<"Brand"> | string | null
  slogan?: Prisma.StringNullableFilter<"Brand"> | string | null
  phoneNumber?: Prisma.StringNullableFilter<"Brand"> | string | null
  whatsapp?: Prisma.StringNullableFilter<"Brand"> | string | null
  instagram?: Prisma.StringNullableFilter<"Brand"> | string | null
  tiktok?: Prisma.StringNullableFilter<"Brand"> | string | null
  facebook?: Prisma.StringNullableFilter<"Brand"> | string | null
  website?: Prisma.StringNullableFilter<"Brand"> | string | null
  createdAt?: Prisma.DateTimeFilter<"Brand"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Brand"> | Date | string
  workspaceId?: Prisma.StringFilter<"Brand"> | string
  workspace?: Prisma.XOR<Prisma.WorkspaceScalarRelationFilter, Prisma.WorkspaceWhereInput>
  spots?: Prisma.SpotListRelationFilter
  addresses?: Prisma.BrandAddressListRelationFilter
}, "id">

export type BrandOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  segment?: Prisma.SortOrder
  responsible?: Prisma.SortOrderInput | Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  logoUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  slogan?: Prisma.SortOrderInput | Prisma.SortOrder
  phoneNumber?: Prisma.SortOrderInput | Prisma.SortOrder
  whatsapp?: Prisma.SortOrderInput | Prisma.SortOrder
  instagram?: Prisma.SortOrderInput | Prisma.SortOrder
  tiktok?: Prisma.SortOrderInput | Prisma.SortOrder
  facebook?: Prisma.SortOrderInput | Prisma.SortOrder
  website?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  workspaceId?: Prisma.SortOrder
  _count?: Prisma.BrandCountOrderByAggregateInput
  _max?: Prisma.BrandMaxOrderByAggregateInput
  _min?: Prisma.BrandMinOrderByAggregateInput
}

export type BrandScalarWhereWithAggregatesInput = {
  AND?: Prisma.BrandScalarWhereWithAggregatesInput | Prisma.BrandScalarWhereWithAggregatesInput[]
  OR?: Prisma.BrandScalarWhereWithAggregatesInput[]
  NOT?: Prisma.BrandScalarWhereWithAggregatesInput | Prisma.BrandScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Brand"> | string
  name?: Prisma.StringWithAggregatesFilter<"Brand"> | string
  segment?: Prisma.EnumBusinessSegmentWithAggregatesFilter<"Brand"> | $Enums.BusinessSegment
  responsible?: Prisma.StringNullableWithAggregatesFilter<"Brand"> | string | null
  description?: Prisma.StringNullableWithAggregatesFilter<"Brand"> | string | null
  logoUrl?: Prisma.StringNullableWithAggregatesFilter<"Brand"> | string | null
  slogan?: Prisma.StringNullableWithAggregatesFilter<"Brand"> | string | null
  phoneNumber?: Prisma.StringNullableWithAggregatesFilter<"Brand"> | string | null
  whatsapp?: Prisma.StringNullableWithAggregatesFilter<"Brand"> | string | null
  instagram?: Prisma.StringNullableWithAggregatesFilter<"Brand"> | string | null
  tiktok?: Prisma.StringNullableWithAggregatesFilter<"Brand"> | string | null
  facebook?: Prisma.StringNullableWithAggregatesFilter<"Brand"> | string | null
  website?: Prisma.StringNullableWithAggregatesFilter<"Brand"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Brand"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Brand"> | Date | string
  workspaceId?: Prisma.StringWithAggregatesFilter<"Brand"> | string
}

export type BrandCreateInput = {
  id?: string
  name: string
  segment: $Enums.BusinessSegment
  responsible?: string | null
  description?: string | null
  logoUrl?: string | null
  slogan?: string | null
  phoneNumber?: string | null
  whatsapp?: string | null
  instagram?: string | null
  tiktok?: string | null
  facebook?: string | null
  website?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  workspace: Prisma.WorkspaceCreateNestedOneWithoutBrandsInput
  spots?: Prisma.SpotCreateNestedManyWithoutBrandInput
  addresses?: Prisma.BrandAddressCreateNestedManyWithoutBrandInput
}

export type BrandUncheckedCreateInput = {
  id?: string
  name: string
  segment: $Enums.BusinessSegment
  responsible?: string | null
  description?: string | null
  logoUrl?: string | null
  slogan?: string | null
  phoneNumber?: string | null
  whatsapp?: string | null
  instagram?: string | null
  tiktok?: string | null
  facebook?: string | null
  website?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  workspaceId: string
  spots?: Prisma.SpotUncheckedCreateNestedManyWithoutBrandInput
  addresses?: Prisma.BrandAddressUncheckedCreateNestedManyWithoutBrandInput
}

export type BrandUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  segment?: Prisma.EnumBusinessSegmentFieldUpdateOperationsInput | $Enums.BusinessSegment
  responsible?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  logoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  slogan?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  phoneNumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  whatsapp?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  instagram?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tiktok?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  facebook?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  website?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  workspace?: Prisma.WorkspaceUpdateOneRequiredWithoutBrandsNestedInput
  spots?: Prisma.SpotUpdateManyWithoutBrandNestedInput
  addresses?: Prisma.BrandAddressUpdateManyWithoutBrandNestedInput
}

export type BrandUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  segment?: Prisma.EnumBusinessSegmentFieldUpdateOperationsInput | $Enums.BusinessSegment
  responsible?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  logoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  slogan?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  phoneNumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  whatsapp?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  instagram?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tiktok?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  facebook?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  website?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  workspaceId?: Prisma.StringFieldUpdateOperationsInput | string
  spots?: Prisma.SpotUncheckedUpdateManyWithoutBrandNestedInput
  addresses?: Prisma.BrandAddressUncheckedUpdateManyWithoutBrandNestedInput
}

export type BrandCreateManyInput = {
  id?: string
  name: string
  segment: $Enums.BusinessSegment
  responsible?: string | null
  description?: string | null
  logoUrl?: string | null
  slogan?: string | null
  phoneNumber?: string | null
  whatsapp?: string | null
  instagram?: string | null
  tiktok?: string | null
  facebook?: string | null
  website?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  workspaceId: string
}

export type BrandUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  segment?: Prisma.EnumBusinessSegmentFieldUpdateOperationsInput | $Enums.BusinessSegment
  responsible?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  logoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  slogan?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  phoneNumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  whatsapp?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  instagram?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tiktok?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  facebook?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  website?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type BrandUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  segment?: Prisma.EnumBusinessSegmentFieldUpdateOperationsInput | $Enums.BusinessSegment
  responsible?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  logoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  slogan?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  phoneNumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  whatsapp?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  instagram?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tiktok?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  facebook?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  website?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  workspaceId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type BrandCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  segment?: Prisma.SortOrder
  responsible?: Prisma.SortOrder
  description?: Prisma.SortOrder
  logoUrl?: Prisma.SortOrder
  slogan?: Prisma.SortOrder
  phoneNumber?: Prisma.SortOrder
  whatsapp?: Prisma.SortOrder
  instagram?: Prisma.SortOrder
  tiktok?: Prisma.SortOrder
  facebook?: Prisma.SortOrder
  website?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  workspaceId?: Prisma.SortOrder
}

export type BrandMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  segment?: Prisma.SortOrder
  responsible?: Prisma.SortOrder
  description?: Prisma.SortOrder
  logoUrl?: Prisma.SortOrder
  slogan?: Prisma.SortOrder
  phoneNumber?: Prisma.SortOrder
  whatsapp?: Prisma.SortOrder
  instagram?: Prisma.SortOrder
  tiktok?: Prisma.SortOrder
  facebook?: Prisma.SortOrder
  website?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  workspaceId?: Prisma.SortOrder
}

export type BrandMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  segment?: Prisma.SortOrder
  responsible?: Prisma.SortOrder
  description?: Prisma.SortOrder
  logoUrl?: Prisma.SortOrder
  slogan?: Prisma.SortOrder
  phoneNumber?: Prisma.SortOrder
  whatsapp?: Prisma.SortOrder
  instagram?: Prisma.SortOrder
  tiktok?: Prisma.SortOrder
  facebook?: Prisma.SortOrder
  website?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  workspaceId?: Prisma.SortOrder
}

export type BrandScalarRelationFilter = {
  is?: Prisma.BrandWhereInput
  isNot?: Prisma.BrandWhereInput
}

export type BrandNullableScalarRelationFilter = {
  is?: Prisma.BrandWhereInput | null
  isNot?: Prisma.BrandWhereInput | null
}

export type BrandListRelationFilter = {
  every?: Prisma.BrandWhereInput
  some?: Prisma.BrandWhereInput
  none?: Prisma.BrandWhereInput
}

export type BrandOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type StringFieldUpdateOperationsInput = {
  set?: string
}

export type EnumBusinessSegmentFieldUpdateOperationsInput = {
  set?: $Enums.BusinessSegment
}

export type NullableStringFieldUpdateOperationsInput = {
  set?: string | null
}

export type DateTimeFieldUpdateOperationsInput = {
  set?: Date | string
}

export type BrandCreateNestedOneWithoutAddressesInput = {
  create?: Prisma.XOR<Prisma.BrandCreateWithoutAddressesInput, Prisma.BrandUncheckedCreateWithoutAddressesInput>
  connectOrCreate?: Prisma.BrandCreateOrConnectWithoutAddressesInput
  connect?: Prisma.BrandWhereUniqueInput
}

export type BrandUpdateOneRequiredWithoutAddressesNestedInput = {
  create?: Prisma.XOR<Prisma.BrandCreateWithoutAddressesInput, Prisma.BrandUncheckedCreateWithoutAddressesInput>
  connectOrCreate?: Prisma.BrandCreateOrConnectWithoutAddressesInput
  upsert?: Prisma.BrandUpsertWithoutAddressesInput
  connect?: Prisma.BrandWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.BrandUpdateToOneWithWhereWithoutAddressesInput, Prisma.BrandUpdateWithoutAddressesInput>, Prisma.BrandUncheckedUpdateWithoutAddressesInput>
}

export type BrandCreateNestedOneWithoutSpotsInput = {
  create?: Prisma.XOR<Prisma.BrandCreateWithoutSpotsInput, Prisma.BrandUncheckedCreateWithoutSpotsInput>
  connectOrCreate?: Prisma.BrandCreateOrConnectWithoutSpotsInput
  connect?: Prisma.BrandWhereUniqueInput
}

export type BrandUpdateOneWithoutSpotsNestedInput = {
  create?: Prisma.XOR<Prisma.BrandCreateWithoutSpotsInput, Prisma.BrandUncheckedCreateWithoutSpotsInput>
  connectOrCreate?: Prisma.BrandCreateOrConnectWithoutSpotsInput
  upsert?: Prisma.BrandUpsertWithoutSpotsInput
  disconnect?: Prisma.BrandWhereInput | boolean
  delete?: Prisma.BrandWhereInput | boolean
  connect?: Prisma.BrandWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.BrandUpdateToOneWithWhereWithoutSpotsInput, Prisma.BrandUpdateWithoutSpotsInput>, Prisma.BrandUncheckedUpdateWithoutSpotsInput>
}

export type BrandCreateNestedManyWithoutWorkspaceInput = {
  create?: Prisma.XOR<Prisma.BrandCreateWithoutWorkspaceInput, Prisma.BrandUncheckedCreateWithoutWorkspaceInput> | Prisma.BrandCreateWithoutWorkspaceInput[] | Prisma.BrandUncheckedCreateWithoutWorkspaceInput[]
  connectOrCreate?: Prisma.BrandCreateOrConnectWithoutWorkspaceInput | Prisma.BrandCreateOrConnectWithoutWorkspaceInput[]
  createMany?: Prisma.BrandCreateManyWorkspaceInputEnvelope
  connect?: Prisma.BrandWhereUniqueInput | Prisma.BrandWhereUniqueInput[]
}

export type BrandUncheckedCreateNestedManyWithoutWorkspaceInput = {
  create?: Prisma.XOR<Prisma.BrandCreateWithoutWorkspaceInput, Prisma.BrandUncheckedCreateWithoutWorkspaceInput> | Prisma.BrandCreateWithoutWorkspaceInput[] | Prisma.BrandUncheckedCreateWithoutWorkspaceInput[]
  connectOrCreate?: Prisma.BrandCreateOrConnectWithoutWorkspaceInput | Prisma.BrandCreateOrConnectWithoutWorkspaceInput[]
  createMany?: Prisma.BrandCreateManyWorkspaceInputEnvelope
  connect?: Prisma.BrandWhereUniqueInput | Prisma.BrandWhereUniqueInput[]
}

export type BrandUpdateManyWithoutWorkspaceNestedInput = {
  create?: Prisma.XOR<Prisma.BrandCreateWithoutWorkspaceInput, Prisma.BrandUncheckedCreateWithoutWorkspaceInput> | Prisma.BrandCreateWithoutWorkspaceInput[] | Prisma.BrandUncheckedCreateWithoutWorkspaceInput[]
  connectOrCreate?: Prisma.BrandCreateOrConnectWithoutWorkspaceInput | Prisma.BrandCreateOrConnectWithoutWorkspaceInput[]
  upsert?: Prisma.BrandUpsertWithWhereUniqueWithoutWorkspaceInput | Prisma.BrandUpsertWithWhereUniqueWithoutWorkspaceInput[]
  createMany?: Prisma.BrandCreateManyWorkspaceInputEnvelope
  set?: Prisma.BrandWhereUniqueInput | Prisma.BrandWhereUniqueInput[]
  disconnect?: Prisma.BrandWhereUniqueInput | Prisma.BrandWhereUniqueInput[]
  delete?: Prisma.BrandWhereUniqueInput | Prisma.BrandWhereUniqueInput[]
  connect?: Prisma.BrandWhereUniqueInput | Prisma.BrandWhereUniqueInput[]
  update?: Prisma.BrandUpdateWithWhereUniqueWithoutWorkspaceInput | Prisma.BrandUpdateWithWhereUniqueWithoutWorkspaceInput[]
  updateMany?: Prisma.BrandUpdateManyWithWhereWithoutWorkspaceInput | Prisma.BrandUpdateManyWithWhereWithoutWorkspaceInput[]
  deleteMany?: Prisma.BrandScalarWhereInput | Prisma.BrandScalarWhereInput[]
}

export type BrandUncheckedUpdateManyWithoutWorkspaceNestedInput = {
  create?: Prisma.XOR<Prisma.BrandCreateWithoutWorkspaceInput, Prisma.BrandUncheckedCreateWithoutWorkspaceInput> | Prisma.BrandCreateWithoutWorkspaceInput[] | Prisma.BrandUncheckedCreateWithoutWorkspaceInput[]
  connectOrCreate?: Prisma.BrandCreateOrConnectWithoutWorkspaceInput | Prisma.BrandCreateOrConnectWithoutWorkspaceInput[]
  upsert?: Prisma.BrandUpsertWithWhereUniqueWithoutWorkspaceInput | Prisma.BrandUpsertWithWhereUniqueWithoutWorkspaceInput[]
  createMany?: Prisma.BrandCreateManyWorkspaceInputEnvelope
  set?: Prisma.BrandWhereUniqueInput | Prisma.BrandWhereUniqueInput[]
  disconnect?: Prisma.BrandWhereUniqueInput | Prisma.BrandWhereUniqueInput[]
  delete?: Prisma.BrandWhereUniqueInput | Prisma.BrandWhereUniqueInput[]
  connect?: Prisma.BrandWhereUniqueInput | Prisma.BrandWhereUniqueInput[]
  update?: Prisma.BrandUpdateWithWhereUniqueWithoutWorkspaceInput | Prisma.BrandUpdateWithWhereUniqueWithoutWorkspaceInput[]
  updateMany?: Prisma.BrandUpdateManyWithWhereWithoutWorkspaceInput | Prisma.BrandUpdateManyWithWhereWithoutWorkspaceInput[]
  deleteMany?: Prisma.BrandScalarWhereInput | Prisma.BrandScalarWhereInput[]
}

export type BrandCreateWithoutAddressesInput = {
  id?: string
  name: string
  segment: $Enums.BusinessSegment
  responsible?: string | null
  description?: string | null
  logoUrl?: string | null
  slogan?: string | null
  phoneNumber?: string | null
  whatsapp?: string | null
  instagram?: string | null
  tiktok?: string | null
  facebook?: string | null
  website?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  workspace: Prisma.WorkspaceCreateNestedOneWithoutBrandsInput
  spots?: Prisma.SpotCreateNestedManyWithoutBrandInput
}

export type BrandUncheckedCreateWithoutAddressesInput = {
  id?: string
  name: string
  segment: $Enums.BusinessSegment
  responsible?: string | null
  description?: string | null
  logoUrl?: string | null
  slogan?: string | null
  phoneNumber?: string | null
  whatsapp?: string | null
  instagram?: string | null
  tiktok?: string | null
  facebook?: string | null
  website?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  workspaceId: string
  spots?: Prisma.SpotUncheckedCreateNestedManyWithoutBrandInput
}

export type BrandCreateOrConnectWithoutAddressesInput = {
  where: Prisma.BrandWhereUniqueInput
  create: Prisma.XOR<Prisma.BrandCreateWithoutAddressesInput, Prisma.BrandUncheckedCreateWithoutAddressesInput>
}

export type BrandUpsertWithoutAddressesInput = {
  update: Prisma.XOR<Prisma.BrandUpdateWithoutAddressesInput, Prisma.BrandUncheckedUpdateWithoutAddressesInput>
  create: Prisma.XOR<Prisma.BrandCreateWithoutAddressesInput, Prisma.BrandUncheckedCreateWithoutAddressesInput>
  where?: Prisma.BrandWhereInput
}

export type BrandUpdateToOneWithWhereWithoutAddressesInput = {
  where?: Prisma.BrandWhereInput
  data: Prisma.XOR<Prisma.BrandUpdateWithoutAddressesInput, Prisma.BrandUncheckedUpdateWithoutAddressesInput>
}

export type BrandUpdateWithoutAddressesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  segment?: Prisma.EnumBusinessSegmentFieldUpdateOperationsInput | $Enums.BusinessSegment
  responsible?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  logoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  slogan?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  phoneNumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  whatsapp?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  instagram?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tiktok?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  facebook?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  website?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  workspace?: Prisma.WorkspaceUpdateOneRequiredWithoutBrandsNestedInput
  spots?: Prisma.SpotUpdateManyWithoutBrandNestedInput
}

export type BrandUncheckedUpdateWithoutAddressesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  segment?: Prisma.EnumBusinessSegmentFieldUpdateOperationsInput | $Enums.BusinessSegment
  responsible?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  logoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  slogan?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  phoneNumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  whatsapp?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  instagram?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tiktok?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  facebook?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  website?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  workspaceId?: Prisma.StringFieldUpdateOperationsInput | string
  spots?: Prisma.SpotUncheckedUpdateManyWithoutBrandNestedInput
}

export type BrandCreateWithoutSpotsInput = {
  id?: string
  name: string
  segment: $Enums.BusinessSegment
  responsible?: string | null
  description?: string | null
  logoUrl?: string | null
  slogan?: string | null
  phoneNumber?: string | null
  whatsapp?: string | null
  instagram?: string | null
  tiktok?: string | null
  facebook?: string | null
  website?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  workspace: Prisma.WorkspaceCreateNestedOneWithoutBrandsInput
  addresses?: Prisma.BrandAddressCreateNestedManyWithoutBrandInput
}

export type BrandUncheckedCreateWithoutSpotsInput = {
  id?: string
  name: string
  segment: $Enums.BusinessSegment
  responsible?: string | null
  description?: string | null
  logoUrl?: string | null
  slogan?: string | null
  phoneNumber?: string | null
  whatsapp?: string | null
  instagram?: string | null
  tiktok?: string | null
  facebook?: string | null
  website?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  workspaceId: string
  addresses?: Prisma.BrandAddressUncheckedCreateNestedManyWithoutBrandInput
}

export type BrandCreateOrConnectWithoutSpotsInput = {
  where: Prisma.BrandWhereUniqueInput
  create: Prisma.XOR<Prisma.BrandCreateWithoutSpotsInput, Prisma.BrandUncheckedCreateWithoutSpotsInput>
}

export type BrandUpsertWithoutSpotsInput = {
  update: Prisma.XOR<Prisma.BrandUpdateWithoutSpotsInput, Prisma.BrandUncheckedUpdateWithoutSpotsInput>
  create: Prisma.XOR<Prisma.BrandCreateWithoutSpotsInput, Prisma.BrandUncheckedCreateWithoutSpotsInput>
  where?: Prisma.BrandWhereInput
}

export type BrandUpdateToOneWithWhereWithoutSpotsInput = {
  where?: Prisma.BrandWhereInput
  data: Prisma.XOR<Prisma.BrandUpdateWithoutSpotsInput, Prisma.BrandUncheckedUpdateWithoutSpotsInput>
}

export type BrandUpdateWithoutSpotsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  segment?: Prisma.EnumBusinessSegmentFieldUpdateOperationsInput | $Enums.BusinessSegment
  responsible?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  logoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  slogan?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  phoneNumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  whatsapp?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  instagram?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tiktok?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  facebook?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  website?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  workspace?: Prisma.WorkspaceUpdateOneRequiredWithoutBrandsNestedInput
  addresses?: Prisma.BrandAddressUpdateManyWithoutBrandNestedInput
}

export type BrandUncheckedUpdateWithoutSpotsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  segment?: Prisma.EnumBusinessSegmentFieldUpdateOperationsInput | $Enums.BusinessSegment
  responsible?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  logoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  slogan?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  phoneNumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  whatsapp?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  instagram?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tiktok?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  facebook?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  website?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  workspaceId?: Prisma.StringFieldUpdateOperationsInput | string
  addresses?: Prisma.BrandAddressUncheckedUpdateManyWithoutBrandNestedInput
}

export type BrandCreateWithoutWorkspaceInput = {
  id?: string
  name: string
  segment: $Enums.BusinessSegment
  responsible?: string | null
  description?: string | null
  logoUrl?: string | null
  slogan?: string | null
  phoneNumber?: string | null
  whatsapp?: string | null
  instagram?: string | null
  tiktok?: string | null
  facebook?: string | null
  website?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  spots?: Prisma.SpotCreateNestedManyWithoutBrandInput
  addresses?: Prisma.BrandAddressCreateNestedManyWithoutBrandInput
}

export type BrandUncheckedCreateWithoutWorkspaceInput = {
  id?: string
  name: string
  segment: $Enums.BusinessSegment
  responsible?: string | null
  description?: string | null
  logoUrl?: string | null
  slogan?: string | null
  phoneNumber?: string | null
  whatsapp?: string | null
  instagram?: string | null
  tiktok?: string | null
  facebook?: string | null
  website?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  spots?: Prisma.SpotUncheckedCreateNestedManyWithoutBrandInput
  addresses?: Prisma.BrandAddressUncheckedCreateNestedManyWithoutBrandInput
}

export type BrandCreateOrConnectWithoutWorkspaceInput = {
  where: Prisma.BrandWhereUniqueInput
  create: Prisma.XOR<Prisma.BrandCreateWithoutWorkspaceInput, Prisma.BrandUncheckedCreateWithoutWorkspaceInput>
}

export type BrandCreateManyWorkspaceInputEnvelope = {
  data: Prisma.BrandCreateManyWorkspaceInput | Prisma.BrandCreateManyWorkspaceInput[]
  skipDuplicates?: boolean
}

export type BrandUpsertWithWhereUniqueWithoutWorkspaceInput = {
  where: Prisma.BrandWhereUniqueInput
  update: Prisma.XOR<Prisma.BrandUpdateWithoutWorkspaceInput, Prisma.BrandUncheckedUpdateWithoutWorkspaceInput>
  create: Prisma.XOR<Prisma.BrandCreateWithoutWorkspaceInput, Prisma.BrandUncheckedCreateWithoutWorkspaceInput>
}

export type BrandUpdateWithWhereUniqueWithoutWorkspaceInput = {
  where: Prisma.BrandWhereUniqueInput
  data: Prisma.XOR<Prisma.BrandUpdateWithoutWorkspaceInput, Prisma.BrandUncheckedUpdateWithoutWorkspaceInput>
}

export type BrandUpdateManyWithWhereWithoutWorkspaceInput = {
  where: Prisma.BrandScalarWhereInput
  data: Prisma.XOR<Prisma.BrandUpdateManyMutationInput, Prisma.BrandUncheckedUpdateManyWithoutWorkspaceInput>
}

export type BrandScalarWhereInput = {
  AND?: Prisma.BrandScalarWhereInput | Prisma.BrandScalarWhereInput[]
  OR?: Prisma.BrandScalarWhereInput[]
  NOT?: Prisma.BrandScalarWhereInput | Prisma.BrandScalarWhereInput[]
  id?: Prisma.StringFilter<"Brand"> | string
  name?: Prisma.StringFilter<"Brand"> | string
  segment?: Prisma.EnumBusinessSegmentFilter<"Brand"> | $Enums.BusinessSegment
  responsible?: Prisma.StringNullableFilter<"Brand"> | string | null
  description?: Prisma.StringNullableFilter<"Brand"> | string | null
  logoUrl?: Prisma.StringNullableFilter<"Brand"> | string | null
  slogan?: Prisma.StringNullableFilter<"Brand"> | string | null
  phoneNumber?: Prisma.StringNullableFilter<"Brand"> | string | null
  whatsapp?: Prisma.StringNullableFilter<"Brand"> | string | null
  instagram?: Prisma.StringNullableFilter<"Brand"> | string | null
  tiktok?: Prisma.StringNullableFilter<"Brand"> | string | null
  facebook?: Prisma.StringNullableFilter<"Brand"> | string | null
  website?: Prisma.StringNullableFilter<"Brand"> | string | null
  createdAt?: Prisma.DateTimeFilter<"Brand"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Brand"> | Date | string
  workspaceId?: Prisma.StringFilter<"Brand"> | string
}

export type BrandCreateManyWorkspaceInput = {
  id?: string
  name: string
  segment: $Enums.BusinessSegment
  responsible?: string | null
  description?: string | null
  logoUrl?: string | null
  slogan?: string | null
  phoneNumber?: string | null
  whatsapp?: string | null
  instagram?: string | null
  tiktok?: string | null
  facebook?: string | null
  website?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type BrandUpdateWithoutWorkspaceInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  segment?: Prisma.EnumBusinessSegmentFieldUpdateOperationsInput | $Enums.BusinessSegment
  responsible?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  logoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  slogan?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  phoneNumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  whatsapp?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  instagram?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tiktok?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  facebook?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  website?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  spots?: Prisma.SpotUpdateManyWithoutBrandNestedInput
  addresses?: Prisma.BrandAddressUpdateManyWithoutBrandNestedInput
}

export type BrandUncheckedUpdateWithoutWorkspaceInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  segment?: Prisma.EnumBusinessSegmentFieldUpdateOperationsInput | $Enums.BusinessSegment
  responsible?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  logoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  slogan?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  phoneNumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  whatsapp?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  instagram?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tiktok?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  facebook?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  website?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  spots?: Prisma.SpotUncheckedUpdateManyWithoutBrandNestedInput
  addresses?: Prisma.BrandAddressUncheckedUpdateManyWithoutBrandNestedInput
}

export type BrandUncheckedUpdateManyWithoutWorkspaceInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  segment?: Prisma.EnumBusinessSegmentFieldUpdateOperationsInput | $Enums.BusinessSegment
  responsible?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  logoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  slogan?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  phoneNumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  whatsapp?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  instagram?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tiktok?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  facebook?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  website?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type BrandCountOutputType
 */

export type BrandCountOutputType = {
  spots: number
  addresses: number
}

export type BrandCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  spots?: boolean | BrandCountOutputTypeCountSpotsArgs
  addresses?: boolean | BrandCountOutputTypeCountAddressesArgs
}

/**
 * BrandCountOutputType without action
 */
export type BrandCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BrandCountOutputType
   */
  select?: Prisma.BrandCountOutputTypeSelect<ExtArgs> | null
}

/**
 * BrandCountOutputType without action
 */
export type BrandCountOutputTypeCountSpotsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.SpotWhereInput
}

/**
 * BrandCountOutputType without action
 */
export type BrandCountOutputTypeCountAddressesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.BrandAddressWhereInput
}


export type BrandSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  segment?: boolean
  responsible?: boolean
  description?: boolean
  logoUrl?: boolean
  slogan?: boolean
  phoneNumber?: boolean
  whatsapp?: boolean
  instagram?: boolean
  tiktok?: boolean
  facebook?: boolean
  website?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  workspaceId?: boolean
  workspace?: boolean | Prisma.WorkspaceDefaultArgs<ExtArgs>
  spots?: boolean | Prisma.Brand$spotsArgs<ExtArgs>
  addresses?: boolean | Prisma.Brand$addressesArgs<ExtArgs>
  _count?: boolean | Prisma.BrandCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["brand"]>

export type BrandSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  segment?: boolean
  responsible?: boolean
  description?: boolean
  logoUrl?: boolean
  slogan?: boolean
  phoneNumber?: boolean
  whatsapp?: boolean
  instagram?: boolean
  tiktok?: boolean
  facebook?: boolean
  website?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  workspaceId?: boolean
  workspace?: boolean | Prisma.WorkspaceDefaultArgs<ExtArgs>
}, ExtArgs["result"]["brand"]>

export type BrandSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  segment?: boolean
  responsible?: boolean
  description?: boolean
  logoUrl?: boolean
  slogan?: boolean
  phoneNumber?: boolean
  whatsapp?: boolean
  instagram?: boolean
  tiktok?: boolean
  facebook?: boolean
  website?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  workspaceId?: boolean
  workspace?: boolean | Prisma.WorkspaceDefaultArgs<ExtArgs>
}, ExtArgs["result"]["brand"]>

export type BrandSelectScalar = {
  id?: boolean
  name?: boolean
  segment?: boolean
  responsible?: boolean
  description?: boolean
  logoUrl?: boolean
  slogan?: boolean
  phoneNumber?: boolean
  whatsapp?: boolean
  instagram?: boolean
  tiktok?: boolean
  facebook?: boolean
  website?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  workspaceId?: boolean
}

export type BrandOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "segment" | "responsible" | "description" | "logoUrl" | "slogan" | "phoneNumber" | "whatsapp" | "instagram" | "tiktok" | "facebook" | "website" | "createdAt" | "updatedAt" | "workspaceId", ExtArgs["result"]["brand"]>
export type BrandInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  workspace?: boolean | Prisma.WorkspaceDefaultArgs<ExtArgs>
  spots?: boolean | Prisma.Brand$spotsArgs<ExtArgs>
  addresses?: boolean | Prisma.Brand$addressesArgs<ExtArgs>
  _count?: boolean | Prisma.BrandCountOutputTypeDefaultArgs<ExtArgs>
}
export type BrandIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  workspace?: boolean | Prisma.WorkspaceDefaultArgs<ExtArgs>
}
export type BrandIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  workspace?: boolean | Prisma.WorkspaceDefaultArgs<ExtArgs>
}

export type $BrandPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Brand"
  objects: {
    workspace: Prisma.$WorkspacePayload<ExtArgs>
    spots: Prisma.$SpotPayload<ExtArgs>[]
    addresses: Prisma.$BrandAddressPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    name: string
    segment: $Enums.BusinessSegment
    responsible: string | null
    description: string | null
    logoUrl: string | null
    slogan: string | null
    phoneNumber: string | null
    whatsapp: string | null
    instagram: string | null
    tiktok: string | null
    facebook: string | null
    website: string | null
    createdAt: Date
    updatedAt: Date
    workspaceId: string
  }, ExtArgs["result"]["brand"]>
  composites: {}
}

export type BrandGetPayload<S extends boolean | null | undefined | BrandDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$BrandPayload, S>

export type BrandCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<BrandFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: BrandCountAggregateInputType | true
  }

export interface BrandDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Brand'], meta: { name: 'Brand' } }
  /**
   * Find zero or one Brand that matches the filter.
   * @param {BrandFindUniqueArgs} args - Arguments to find a Brand
   * @example
   * // Get one Brand
   * const brand = await prisma.brand.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends BrandFindUniqueArgs>(args: Prisma.SelectSubset<T, BrandFindUniqueArgs<ExtArgs>>): Prisma.Prisma__BrandClient<runtime.Types.Result.GetResult<Prisma.$BrandPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Brand that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {BrandFindUniqueOrThrowArgs} args - Arguments to find a Brand
   * @example
   * // Get one Brand
   * const brand = await prisma.brand.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends BrandFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, BrandFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__BrandClient<runtime.Types.Result.GetResult<Prisma.$BrandPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Brand that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BrandFindFirstArgs} args - Arguments to find a Brand
   * @example
   * // Get one Brand
   * const brand = await prisma.brand.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends BrandFindFirstArgs>(args?: Prisma.SelectSubset<T, BrandFindFirstArgs<ExtArgs>>): Prisma.Prisma__BrandClient<runtime.Types.Result.GetResult<Prisma.$BrandPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Brand that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BrandFindFirstOrThrowArgs} args - Arguments to find a Brand
   * @example
   * // Get one Brand
   * const brand = await prisma.brand.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends BrandFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, BrandFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__BrandClient<runtime.Types.Result.GetResult<Prisma.$BrandPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Brands that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BrandFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Brands
   * const brands = await prisma.brand.findMany()
   * 
   * // Get first 10 Brands
   * const brands = await prisma.brand.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const brandWithIdOnly = await prisma.brand.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends BrandFindManyArgs>(args?: Prisma.SelectSubset<T, BrandFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BrandPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Brand.
   * @param {BrandCreateArgs} args - Arguments to create a Brand.
   * @example
   * // Create one Brand
   * const Brand = await prisma.brand.create({
   *   data: {
   *     // ... data to create a Brand
   *   }
   * })
   * 
   */
  create<T extends BrandCreateArgs>(args: Prisma.SelectSubset<T, BrandCreateArgs<ExtArgs>>): Prisma.Prisma__BrandClient<runtime.Types.Result.GetResult<Prisma.$BrandPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Brands.
   * @param {BrandCreateManyArgs} args - Arguments to create many Brands.
   * @example
   * // Create many Brands
   * const brand = await prisma.brand.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends BrandCreateManyArgs>(args?: Prisma.SelectSubset<T, BrandCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Brands and returns the data saved in the database.
   * @param {BrandCreateManyAndReturnArgs} args - Arguments to create many Brands.
   * @example
   * // Create many Brands
   * const brand = await prisma.brand.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Brands and only return the `id`
   * const brandWithIdOnly = await prisma.brand.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends BrandCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, BrandCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BrandPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Brand.
   * @param {BrandDeleteArgs} args - Arguments to delete one Brand.
   * @example
   * // Delete one Brand
   * const Brand = await prisma.brand.delete({
   *   where: {
   *     // ... filter to delete one Brand
   *   }
   * })
   * 
   */
  delete<T extends BrandDeleteArgs>(args: Prisma.SelectSubset<T, BrandDeleteArgs<ExtArgs>>): Prisma.Prisma__BrandClient<runtime.Types.Result.GetResult<Prisma.$BrandPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Brand.
   * @param {BrandUpdateArgs} args - Arguments to update one Brand.
   * @example
   * // Update one Brand
   * const brand = await prisma.brand.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends BrandUpdateArgs>(args: Prisma.SelectSubset<T, BrandUpdateArgs<ExtArgs>>): Prisma.Prisma__BrandClient<runtime.Types.Result.GetResult<Prisma.$BrandPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Brands.
   * @param {BrandDeleteManyArgs} args - Arguments to filter Brands to delete.
   * @example
   * // Delete a few Brands
   * const { count } = await prisma.brand.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends BrandDeleteManyArgs>(args?: Prisma.SelectSubset<T, BrandDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Brands.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BrandUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Brands
   * const brand = await prisma.brand.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends BrandUpdateManyArgs>(args: Prisma.SelectSubset<T, BrandUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Brands and returns the data updated in the database.
   * @param {BrandUpdateManyAndReturnArgs} args - Arguments to update many Brands.
   * @example
   * // Update many Brands
   * const brand = await prisma.brand.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Brands and only return the `id`
   * const brandWithIdOnly = await prisma.brand.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends BrandUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, BrandUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BrandPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Brand.
   * @param {BrandUpsertArgs} args - Arguments to update or create a Brand.
   * @example
   * // Update or create a Brand
   * const brand = await prisma.brand.upsert({
   *   create: {
   *     // ... data to create a Brand
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Brand we want to update
   *   }
   * })
   */
  upsert<T extends BrandUpsertArgs>(args: Prisma.SelectSubset<T, BrandUpsertArgs<ExtArgs>>): Prisma.Prisma__BrandClient<runtime.Types.Result.GetResult<Prisma.$BrandPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Brands.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BrandCountArgs} args - Arguments to filter Brands to count.
   * @example
   * // Count the number of Brands
   * const count = await prisma.brand.count({
   *   where: {
   *     // ... the filter for the Brands we want to count
   *   }
   * })
  **/
  count<T extends BrandCountArgs>(
    args?: Prisma.Subset<T, BrandCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], BrandCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Brand.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BrandAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends BrandAggregateArgs>(args: Prisma.Subset<T, BrandAggregateArgs>): Prisma.PrismaPromise<GetBrandAggregateType<T>>

  /**
   * Group by Brand.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BrandGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends BrandGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: BrandGroupByArgs['orderBy'] }
      : { orderBy?: BrandGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, BrandGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetBrandGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Brand model
 */
readonly fields: BrandFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Brand.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__BrandClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  workspace<T extends Prisma.WorkspaceDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.WorkspaceDefaultArgs<ExtArgs>>): Prisma.Prisma__WorkspaceClient<runtime.Types.Result.GetResult<Prisma.$WorkspacePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  spots<T extends Prisma.Brand$spotsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Brand$spotsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SpotPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  addresses<T extends Prisma.Brand$addressesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Brand$addressesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BrandAddressPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Brand model
 */
export interface BrandFieldRefs {
  readonly id: Prisma.FieldRef<"Brand", 'String'>
  readonly name: Prisma.FieldRef<"Brand", 'String'>
  readonly segment: Prisma.FieldRef<"Brand", 'BusinessSegment'>
  readonly responsible: Prisma.FieldRef<"Brand", 'String'>
  readonly description: Prisma.FieldRef<"Brand", 'String'>
  readonly logoUrl: Prisma.FieldRef<"Brand", 'String'>
  readonly slogan: Prisma.FieldRef<"Brand", 'String'>
  readonly phoneNumber: Prisma.FieldRef<"Brand", 'String'>
  readonly whatsapp: Prisma.FieldRef<"Brand", 'String'>
  readonly instagram: Prisma.FieldRef<"Brand", 'String'>
  readonly tiktok: Prisma.FieldRef<"Brand", 'String'>
  readonly facebook: Prisma.FieldRef<"Brand", 'String'>
  readonly website: Prisma.FieldRef<"Brand", 'String'>
  readonly createdAt: Prisma.FieldRef<"Brand", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Brand", 'DateTime'>
  readonly workspaceId: Prisma.FieldRef<"Brand", 'String'>
}
    

// Custom InputTypes
/**
 * Brand findUnique
 */
export type BrandFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Brand
   */
  select?: Prisma.BrandSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Brand
   */
  omit?: Prisma.BrandOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BrandInclude<ExtArgs> | null
  /**
   * Filter, which Brand to fetch.
   */
  where: Prisma.BrandWhereUniqueInput
}

/**
 * Brand findUniqueOrThrow
 */
export type BrandFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Brand
   */
  select?: Prisma.BrandSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Brand
   */
  omit?: Prisma.BrandOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BrandInclude<ExtArgs> | null
  /**
   * Filter, which Brand to fetch.
   */
  where: Prisma.BrandWhereUniqueInput
}

/**
 * Brand findFirst
 */
export type BrandFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Brand
   */
  select?: Prisma.BrandSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Brand
   */
  omit?: Prisma.BrandOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BrandInclude<ExtArgs> | null
  /**
   * Filter, which Brand to fetch.
   */
  where?: Prisma.BrandWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Brands to fetch.
   */
  orderBy?: Prisma.BrandOrderByWithRelationInput | Prisma.BrandOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Brands.
   */
  cursor?: Prisma.BrandWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Brands from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Brands.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Brands.
   */
  distinct?: Prisma.BrandScalarFieldEnum | Prisma.BrandScalarFieldEnum[]
}

/**
 * Brand findFirstOrThrow
 */
export type BrandFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Brand
   */
  select?: Prisma.BrandSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Brand
   */
  omit?: Prisma.BrandOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BrandInclude<ExtArgs> | null
  /**
   * Filter, which Brand to fetch.
   */
  where?: Prisma.BrandWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Brands to fetch.
   */
  orderBy?: Prisma.BrandOrderByWithRelationInput | Prisma.BrandOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Brands.
   */
  cursor?: Prisma.BrandWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Brands from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Brands.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Brands.
   */
  distinct?: Prisma.BrandScalarFieldEnum | Prisma.BrandScalarFieldEnum[]
}

/**
 * Brand findMany
 */
export type BrandFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Brand
   */
  select?: Prisma.BrandSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Brand
   */
  omit?: Prisma.BrandOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BrandInclude<ExtArgs> | null
  /**
   * Filter, which Brands to fetch.
   */
  where?: Prisma.BrandWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Brands to fetch.
   */
  orderBy?: Prisma.BrandOrderByWithRelationInput | Prisma.BrandOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Brands.
   */
  cursor?: Prisma.BrandWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Brands from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Brands.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Brands.
   */
  distinct?: Prisma.BrandScalarFieldEnum | Prisma.BrandScalarFieldEnum[]
}

/**
 * Brand create
 */
export type BrandCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Brand
   */
  select?: Prisma.BrandSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Brand
   */
  omit?: Prisma.BrandOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BrandInclude<ExtArgs> | null
  /**
   * The data needed to create a Brand.
   */
  data: Prisma.XOR<Prisma.BrandCreateInput, Prisma.BrandUncheckedCreateInput>
}

/**
 * Brand createMany
 */
export type BrandCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Brands.
   */
  data: Prisma.BrandCreateManyInput | Prisma.BrandCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Brand createManyAndReturn
 */
export type BrandCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Brand
   */
  select?: Prisma.BrandSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Brand
   */
  omit?: Prisma.BrandOmit<ExtArgs> | null
  /**
   * The data used to create many Brands.
   */
  data: Prisma.BrandCreateManyInput | Prisma.BrandCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BrandIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Brand update
 */
export type BrandUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Brand
   */
  select?: Prisma.BrandSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Brand
   */
  omit?: Prisma.BrandOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BrandInclude<ExtArgs> | null
  /**
   * The data needed to update a Brand.
   */
  data: Prisma.XOR<Prisma.BrandUpdateInput, Prisma.BrandUncheckedUpdateInput>
  /**
   * Choose, which Brand to update.
   */
  where: Prisma.BrandWhereUniqueInput
}

/**
 * Brand updateMany
 */
export type BrandUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Brands.
   */
  data: Prisma.XOR<Prisma.BrandUpdateManyMutationInput, Prisma.BrandUncheckedUpdateManyInput>
  /**
   * Filter which Brands to update
   */
  where?: Prisma.BrandWhereInput
  /**
   * Limit how many Brands to update.
   */
  limit?: number
}

/**
 * Brand updateManyAndReturn
 */
export type BrandUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Brand
   */
  select?: Prisma.BrandSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Brand
   */
  omit?: Prisma.BrandOmit<ExtArgs> | null
  /**
   * The data used to update Brands.
   */
  data: Prisma.XOR<Prisma.BrandUpdateManyMutationInput, Prisma.BrandUncheckedUpdateManyInput>
  /**
   * Filter which Brands to update
   */
  where?: Prisma.BrandWhereInput
  /**
   * Limit how many Brands to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BrandIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Brand upsert
 */
export type BrandUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Brand
   */
  select?: Prisma.BrandSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Brand
   */
  omit?: Prisma.BrandOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BrandInclude<ExtArgs> | null
  /**
   * The filter to search for the Brand to update in case it exists.
   */
  where: Prisma.BrandWhereUniqueInput
  /**
   * In case the Brand found by the `where` argument doesn't exist, create a new Brand with this data.
   */
  create: Prisma.XOR<Prisma.BrandCreateInput, Prisma.BrandUncheckedCreateInput>
  /**
   * In case the Brand was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.BrandUpdateInput, Prisma.BrandUncheckedUpdateInput>
}

/**
 * Brand delete
 */
export type BrandDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Brand
   */
  select?: Prisma.BrandSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Brand
   */
  omit?: Prisma.BrandOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BrandInclude<ExtArgs> | null
  /**
   * Filter which Brand to delete.
   */
  where: Prisma.BrandWhereUniqueInput
}

/**
 * Brand deleteMany
 */
export type BrandDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Brands to delete
   */
  where?: Prisma.BrandWhereInput
  /**
   * Limit how many Brands to delete.
   */
  limit?: number
}

/**
 * Brand.spots
 */
export type Brand$spotsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Spot
   */
  select?: Prisma.SpotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Spot
   */
  omit?: Prisma.SpotOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SpotInclude<ExtArgs> | null
  where?: Prisma.SpotWhereInput
  orderBy?: Prisma.SpotOrderByWithRelationInput | Prisma.SpotOrderByWithRelationInput[]
  cursor?: Prisma.SpotWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.SpotScalarFieldEnum | Prisma.SpotScalarFieldEnum[]
}

/**
 * Brand.addresses
 */
export type Brand$addressesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BrandAddress
   */
  select?: Prisma.BrandAddressSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BrandAddress
   */
  omit?: Prisma.BrandAddressOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BrandAddressInclude<ExtArgs> | null
  where?: Prisma.BrandAddressWhereInput
  orderBy?: Prisma.BrandAddressOrderByWithRelationInput | Prisma.BrandAddressOrderByWithRelationInput[]
  cursor?: Prisma.BrandAddressWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.BrandAddressScalarFieldEnum | Prisma.BrandAddressScalarFieldEnum[]
}

/**
 * Brand without action
 */
export type BrandDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Brand
   */
  select?: Prisma.BrandSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Brand
   */
  omit?: Prisma.BrandOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BrandInclude<ExtArgs> | null
}
