
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `InvoiceSummary` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model InvoiceSummary
 * 
 */
export type InvoiceSummaryModel = runtime.Types.Result.DefaultSelection<Prisma.$InvoiceSummaryPayload>

export type AggregateInvoiceSummary = {
  _count: InvoiceSummaryCountAggregateOutputType | null
  _avg: InvoiceSummaryAvgAggregateOutputType | null
  _sum: InvoiceSummarySumAggregateOutputType | null
  _min: InvoiceSummaryMinAggregateOutputType | null
  _max: InvoiceSummaryMaxAggregateOutputType | null
}

export type InvoiceSummaryAvgAggregateOutputType = {
  availableSpots: number | null
  generatedSpots: number | null
}

export type InvoiceSummarySumAggregateOutputType = {
  availableSpots: number | null
  generatedSpots: number | null
}

export type InvoiceSummaryMinAggregateOutputType = {
  id: string | null
  fromAt: Date | null
  toAt: Date | null
  availableSpots: number | null
  generatedSpots: number | null
  createdAt: Date | null
  updatedAt: Date | null
  subscriptionId: string | null
}

export type InvoiceSummaryMaxAggregateOutputType = {
  id: string | null
  fromAt: Date | null
  toAt: Date | null
  availableSpots: number | null
  generatedSpots: number | null
  createdAt: Date | null
  updatedAt: Date | null
  subscriptionId: string | null
}

export type InvoiceSummaryCountAggregateOutputType = {
  id: number
  fromAt: number
  toAt: number
  availableSpots: number
  generatedSpots: number
  createdAt: number
  updatedAt: number
  subscriptionId: number
  _all: number
}


export type InvoiceSummaryAvgAggregateInputType = {
  availableSpots?: true
  generatedSpots?: true
}

export type InvoiceSummarySumAggregateInputType = {
  availableSpots?: true
  generatedSpots?: true
}

export type InvoiceSummaryMinAggregateInputType = {
  id?: true
  fromAt?: true
  toAt?: true
  availableSpots?: true
  generatedSpots?: true
  createdAt?: true
  updatedAt?: true
  subscriptionId?: true
}

export type InvoiceSummaryMaxAggregateInputType = {
  id?: true
  fromAt?: true
  toAt?: true
  availableSpots?: true
  generatedSpots?: true
  createdAt?: true
  updatedAt?: true
  subscriptionId?: true
}

export type InvoiceSummaryCountAggregateInputType = {
  id?: true
  fromAt?: true
  toAt?: true
  availableSpots?: true
  generatedSpots?: true
  createdAt?: true
  updatedAt?: true
  subscriptionId?: true
  _all?: true
}

export type InvoiceSummaryAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which InvoiceSummary to aggregate.
   */
  where?: Prisma.InvoiceSummaryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of InvoiceSummaries to fetch.
   */
  orderBy?: Prisma.InvoiceSummaryOrderByWithRelationInput | Prisma.InvoiceSummaryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.InvoiceSummaryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` InvoiceSummaries from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` InvoiceSummaries.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned InvoiceSummaries
  **/
  _count?: true | InvoiceSummaryCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: InvoiceSummaryAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: InvoiceSummarySumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: InvoiceSummaryMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: InvoiceSummaryMaxAggregateInputType
}

export type GetInvoiceSummaryAggregateType<T extends InvoiceSummaryAggregateArgs> = {
      [P in keyof T & keyof AggregateInvoiceSummary]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateInvoiceSummary[P]>
    : Prisma.GetScalarType<T[P], AggregateInvoiceSummary[P]>
}




export type InvoiceSummaryGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.InvoiceSummaryWhereInput
  orderBy?: Prisma.InvoiceSummaryOrderByWithAggregationInput | Prisma.InvoiceSummaryOrderByWithAggregationInput[]
  by: Prisma.InvoiceSummaryScalarFieldEnum[] | Prisma.InvoiceSummaryScalarFieldEnum
  having?: Prisma.InvoiceSummaryScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: InvoiceSummaryCountAggregateInputType | true
  _avg?: InvoiceSummaryAvgAggregateInputType
  _sum?: InvoiceSummarySumAggregateInputType
  _min?: InvoiceSummaryMinAggregateInputType
  _max?: InvoiceSummaryMaxAggregateInputType
}

export type InvoiceSummaryGroupByOutputType = {
  id: string
  fromAt: Date
  toAt: Date
  availableSpots: number
  generatedSpots: number
  createdAt: Date
  updatedAt: Date
  subscriptionId: string
  _count: InvoiceSummaryCountAggregateOutputType | null
  _avg: InvoiceSummaryAvgAggregateOutputType | null
  _sum: InvoiceSummarySumAggregateOutputType | null
  _min: InvoiceSummaryMinAggregateOutputType | null
  _max: InvoiceSummaryMaxAggregateOutputType | null
}

export type GetInvoiceSummaryGroupByPayload<T extends InvoiceSummaryGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<InvoiceSummaryGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof InvoiceSummaryGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], InvoiceSummaryGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], InvoiceSummaryGroupByOutputType[P]>
      }
    >
  >



export type InvoiceSummaryWhereInput = {
  AND?: Prisma.InvoiceSummaryWhereInput | Prisma.InvoiceSummaryWhereInput[]
  OR?: Prisma.InvoiceSummaryWhereInput[]
  NOT?: Prisma.InvoiceSummaryWhereInput | Prisma.InvoiceSummaryWhereInput[]
  id?: Prisma.StringFilter<"InvoiceSummary"> | string
  fromAt?: Prisma.DateTimeFilter<"InvoiceSummary"> | Date | string
  toAt?: Prisma.DateTimeFilter<"InvoiceSummary"> | Date | string
  availableSpots?: Prisma.IntFilter<"InvoiceSummary"> | number
  generatedSpots?: Prisma.IntFilter<"InvoiceSummary"> | number
  createdAt?: Prisma.DateTimeFilter<"InvoiceSummary"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"InvoiceSummary"> | Date | string
  subscriptionId?: Prisma.StringFilter<"InvoiceSummary"> | string
  subscription?: Prisma.XOR<Prisma.SubscriptionScalarRelationFilter, Prisma.SubscriptionWhereInput>
  charges?: Prisma.ChargeListRelationFilter
}

export type InvoiceSummaryOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  fromAt?: Prisma.SortOrder
  toAt?: Prisma.SortOrder
  availableSpots?: Prisma.SortOrder
  generatedSpots?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  subscriptionId?: Prisma.SortOrder
  subscription?: Prisma.SubscriptionOrderByWithRelationInput
  charges?: Prisma.ChargeOrderByRelationAggregateInput
}

export type InvoiceSummaryWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.InvoiceSummaryWhereInput | Prisma.InvoiceSummaryWhereInput[]
  OR?: Prisma.InvoiceSummaryWhereInput[]
  NOT?: Prisma.InvoiceSummaryWhereInput | Prisma.InvoiceSummaryWhereInput[]
  fromAt?: Prisma.DateTimeFilter<"InvoiceSummary"> | Date | string
  toAt?: Prisma.DateTimeFilter<"InvoiceSummary"> | Date | string
  availableSpots?: Prisma.IntFilter<"InvoiceSummary"> | number
  generatedSpots?: Prisma.IntFilter<"InvoiceSummary"> | number
  createdAt?: Prisma.DateTimeFilter<"InvoiceSummary"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"InvoiceSummary"> | Date | string
  subscriptionId?: Prisma.StringFilter<"InvoiceSummary"> | string
  subscription?: Prisma.XOR<Prisma.SubscriptionScalarRelationFilter, Prisma.SubscriptionWhereInput>
  charges?: Prisma.ChargeListRelationFilter
}, "id">

export type InvoiceSummaryOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  fromAt?: Prisma.SortOrder
  toAt?: Prisma.SortOrder
  availableSpots?: Prisma.SortOrder
  generatedSpots?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  subscriptionId?: Prisma.SortOrder
  _count?: Prisma.InvoiceSummaryCountOrderByAggregateInput
  _avg?: Prisma.InvoiceSummaryAvgOrderByAggregateInput
  _max?: Prisma.InvoiceSummaryMaxOrderByAggregateInput
  _min?: Prisma.InvoiceSummaryMinOrderByAggregateInput
  _sum?: Prisma.InvoiceSummarySumOrderByAggregateInput
}

export type InvoiceSummaryScalarWhereWithAggregatesInput = {
  AND?: Prisma.InvoiceSummaryScalarWhereWithAggregatesInput | Prisma.InvoiceSummaryScalarWhereWithAggregatesInput[]
  OR?: Prisma.InvoiceSummaryScalarWhereWithAggregatesInput[]
  NOT?: Prisma.InvoiceSummaryScalarWhereWithAggregatesInput | Prisma.InvoiceSummaryScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"InvoiceSummary"> | string
  fromAt?: Prisma.DateTimeWithAggregatesFilter<"InvoiceSummary"> | Date | string
  toAt?: Prisma.DateTimeWithAggregatesFilter<"InvoiceSummary"> | Date | string
  availableSpots?: Prisma.IntWithAggregatesFilter<"InvoiceSummary"> | number
  generatedSpots?: Prisma.IntWithAggregatesFilter<"InvoiceSummary"> | number
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"InvoiceSummary"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"InvoiceSummary"> | Date | string
  subscriptionId?: Prisma.StringWithAggregatesFilter<"InvoiceSummary"> | string
}

export type InvoiceSummaryCreateInput = {
  id?: string
  fromAt: Date | string
  toAt: Date | string
  availableSpots: number
  generatedSpots: number
  createdAt?: Date | string
  updatedAt?: Date | string
  subscription: Prisma.SubscriptionCreateNestedOneWithoutInvoicesInput
  charges?: Prisma.ChargeCreateNestedManyWithoutInvoiceSummaryInput
}

export type InvoiceSummaryUncheckedCreateInput = {
  id?: string
  fromAt: Date | string
  toAt: Date | string
  availableSpots: number
  generatedSpots: number
  createdAt?: Date | string
  updatedAt?: Date | string
  subscriptionId: string
  charges?: Prisma.ChargeUncheckedCreateNestedManyWithoutInvoiceSummaryInput
}

export type InvoiceSummaryUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fromAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  toAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  availableSpots?: Prisma.IntFieldUpdateOperationsInput | number
  generatedSpots?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  subscription?: Prisma.SubscriptionUpdateOneRequiredWithoutInvoicesNestedInput
  charges?: Prisma.ChargeUpdateManyWithoutInvoiceSummaryNestedInput
}

export type InvoiceSummaryUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fromAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  toAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  availableSpots?: Prisma.IntFieldUpdateOperationsInput | number
  generatedSpots?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  subscriptionId?: Prisma.StringFieldUpdateOperationsInput | string
  charges?: Prisma.ChargeUncheckedUpdateManyWithoutInvoiceSummaryNestedInput
}

export type InvoiceSummaryCreateManyInput = {
  id?: string
  fromAt: Date | string
  toAt: Date | string
  availableSpots: number
  generatedSpots: number
  createdAt?: Date | string
  updatedAt?: Date | string
  subscriptionId: string
}

export type InvoiceSummaryUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fromAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  toAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  availableSpots?: Prisma.IntFieldUpdateOperationsInput | number
  generatedSpots?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type InvoiceSummaryUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fromAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  toAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  availableSpots?: Prisma.IntFieldUpdateOperationsInput | number
  generatedSpots?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  subscriptionId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type InvoiceSummaryListRelationFilter = {
  every?: Prisma.InvoiceSummaryWhereInput
  some?: Prisma.InvoiceSummaryWhereInput
  none?: Prisma.InvoiceSummaryWhereInput
}

export type InvoiceSummaryOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type InvoiceSummaryCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  fromAt?: Prisma.SortOrder
  toAt?: Prisma.SortOrder
  availableSpots?: Prisma.SortOrder
  generatedSpots?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  subscriptionId?: Prisma.SortOrder
}

export type InvoiceSummaryAvgOrderByAggregateInput = {
  availableSpots?: Prisma.SortOrder
  generatedSpots?: Prisma.SortOrder
}

export type InvoiceSummaryMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  fromAt?: Prisma.SortOrder
  toAt?: Prisma.SortOrder
  availableSpots?: Prisma.SortOrder
  generatedSpots?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  subscriptionId?: Prisma.SortOrder
}

export type InvoiceSummaryMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  fromAt?: Prisma.SortOrder
  toAt?: Prisma.SortOrder
  availableSpots?: Prisma.SortOrder
  generatedSpots?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  subscriptionId?: Prisma.SortOrder
}

export type InvoiceSummarySumOrderByAggregateInput = {
  availableSpots?: Prisma.SortOrder
  generatedSpots?: Prisma.SortOrder
}

export type InvoiceSummaryScalarRelationFilter = {
  is?: Prisma.InvoiceSummaryWhereInput
  isNot?: Prisma.InvoiceSummaryWhereInput
}

export type InvoiceSummaryCreateNestedManyWithoutSubscriptionInput = {
  create?: Prisma.XOR<Prisma.InvoiceSummaryCreateWithoutSubscriptionInput, Prisma.InvoiceSummaryUncheckedCreateWithoutSubscriptionInput> | Prisma.InvoiceSummaryCreateWithoutSubscriptionInput[] | Prisma.InvoiceSummaryUncheckedCreateWithoutSubscriptionInput[]
  connectOrCreate?: Prisma.InvoiceSummaryCreateOrConnectWithoutSubscriptionInput | Prisma.InvoiceSummaryCreateOrConnectWithoutSubscriptionInput[]
  createMany?: Prisma.InvoiceSummaryCreateManySubscriptionInputEnvelope
  connect?: Prisma.InvoiceSummaryWhereUniqueInput | Prisma.InvoiceSummaryWhereUniqueInput[]
}

export type InvoiceSummaryUncheckedCreateNestedManyWithoutSubscriptionInput = {
  create?: Prisma.XOR<Prisma.InvoiceSummaryCreateWithoutSubscriptionInput, Prisma.InvoiceSummaryUncheckedCreateWithoutSubscriptionInput> | Prisma.InvoiceSummaryCreateWithoutSubscriptionInput[] | Prisma.InvoiceSummaryUncheckedCreateWithoutSubscriptionInput[]
  connectOrCreate?: Prisma.InvoiceSummaryCreateOrConnectWithoutSubscriptionInput | Prisma.InvoiceSummaryCreateOrConnectWithoutSubscriptionInput[]
  createMany?: Prisma.InvoiceSummaryCreateManySubscriptionInputEnvelope
  connect?: Prisma.InvoiceSummaryWhereUniqueInput | Prisma.InvoiceSummaryWhereUniqueInput[]
}

export type InvoiceSummaryUpdateManyWithoutSubscriptionNestedInput = {
  create?: Prisma.XOR<Prisma.InvoiceSummaryCreateWithoutSubscriptionInput, Prisma.InvoiceSummaryUncheckedCreateWithoutSubscriptionInput> | Prisma.InvoiceSummaryCreateWithoutSubscriptionInput[] | Prisma.InvoiceSummaryUncheckedCreateWithoutSubscriptionInput[]
  connectOrCreate?: Prisma.InvoiceSummaryCreateOrConnectWithoutSubscriptionInput | Prisma.InvoiceSummaryCreateOrConnectWithoutSubscriptionInput[]
  upsert?: Prisma.InvoiceSummaryUpsertWithWhereUniqueWithoutSubscriptionInput | Prisma.InvoiceSummaryUpsertWithWhereUniqueWithoutSubscriptionInput[]
  createMany?: Prisma.InvoiceSummaryCreateManySubscriptionInputEnvelope
  set?: Prisma.InvoiceSummaryWhereUniqueInput | Prisma.InvoiceSummaryWhereUniqueInput[]
  disconnect?: Prisma.InvoiceSummaryWhereUniqueInput | Prisma.InvoiceSummaryWhereUniqueInput[]
  delete?: Prisma.InvoiceSummaryWhereUniqueInput | Prisma.InvoiceSummaryWhereUniqueInput[]
  connect?: Prisma.InvoiceSummaryWhereUniqueInput | Prisma.InvoiceSummaryWhereUniqueInput[]
  update?: Prisma.InvoiceSummaryUpdateWithWhereUniqueWithoutSubscriptionInput | Prisma.InvoiceSummaryUpdateWithWhereUniqueWithoutSubscriptionInput[]
  updateMany?: Prisma.InvoiceSummaryUpdateManyWithWhereWithoutSubscriptionInput | Prisma.InvoiceSummaryUpdateManyWithWhereWithoutSubscriptionInput[]
  deleteMany?: Prisma.InvoiceSummaryScalarWhereInput | Prisma.InvoiceSummaryScalarWhereInput[]
}

export type InvoiceSummaryUncheckedUpdateManyWithoutSubscriptionNestedInput = {
  create?: Prisma.XOR<Prisma.InvoiceSummaryCreateWithoutSubscriptionInput, Prisma.InvoiceSummaryUncheckedCreateWithoutSubscriptionInput> | Prisma.InvoiceSummaryCreateWithoutSubscriptionInput[] | Prisma.InvoiceSummaryUncheckedCreateWithoutSubscriptionInput[]
  connectOrCreate?: Prisma.InvoiceSummaryCreateOrConnectWithoutSubscriptionInput | Prisma.InvoiceSummaryCreateOrConnectWithoutSubscriptionInput[]
  upsert?: Prisma.InvoiceSummaryUpsertWithWhereUniqueWithoutSubscriptionInput | Prisma.InvoiceSummaryUpsertWithWhereUniqueWithoutSubscriptionInput[]
  createMany?: Prisma.InvoiceSummaryCreateManySubscriptionInputEnvelope
  set?: Prisma.InvoiceSummaryWhereUniqueInput | Prisma.InvoiceSummaryWhereUniqueInput[]
  disconnect?: Prisma.InvoiceSummaryWhereUniqueInput | Prisma.InvoiceSummaryWhereUniqueInput[]
  delete?: Prisma.InvoiceSummaryWhereUniqueInput | Prisma.InvoiceSummaryWhereUniqueInput[]
  connect?: Prisma.InvoiceSummaryWhereUniqueInput | Prisma.InvoiceSummaryWhereUniqueInput[]
  update?: Prisma.InvoiceSummaryUpdateWithWhereUniqueWithoutSubscriptionInput | Prisma.InvoiceSummaryUpdateWithWhereUniqueWithoutSubscriptionInput[]
  updateMany?: Prisma.InvoiceSummaryUpdateManyWithWhereWithoutSubscriptionInput | Prisma.InvoiceSummaryUpdateManyWithWhereWithoutSubscriptionInput[]
  deleteMany?: Prisma.InvoiceSummaryScalarWhereInput | Prisma.InvoiceSummaryScalarWhereInput[]
}

export type InvoiceSummaryCreateNestedOneWithoutChargesInput = {
  create?: Prisma.XOR<Prisma.InvoiceSummaryCreateWithoutChargesInput, Prisma.InvoiceSummaryUncheckedCreateWithoutChargesInput>
  connectOrCreate?: Prisma.InvoiceSummaryCreateOrConnectWithoutChargesInput
  connect?: Prisma.InvoiceSummaryWhereUniqueInput
}

export type InvoiceSummaryUpdateOneRequiredWithoutChargesNestedInput = {
  create?: Prisma.XOR<Prisma.InvoiceSummaryCreateWithoutChargesInput, Prisma.InvoiceSummaryUncheckedCreateWithoutChargesInput>
  connectOrCreate?: Prisma.InvoiceSummaryCreateOrConnectWithoutChargesInput
  upsert?: Prisma.InvoiceSummaryUpsertWithoutChargesInput
  connect?: Prisma.InvoiceSummaryWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.InvoiceSummaryUpdateToOneWithWhereWithoutChargesInput, Prisma.InvoiceSummaryUpdateWithoutChargesInput>, Prisma.InvoiceSummaryUncheckedUpdateWithoutChargesInput>
}

export type InvoiceSummaryCreateWithoutSubscriptionInput = {
  id?: string
  fromAt: Date | string
  toAt: Date | string
  availableSpots: number
  generatedSpots: number
  createdAt?: Date | string
  updatedAt?: Date | string
  charges?: Prisma.ChargeCreateNestedManyWithoutInvoiceSummaryInput
}

export type InvoiceSummaryUncheckedCreateWithoutSubscriptionInput = {
  id?: string
  fromAt: Date | string
  toAt: Date | string
  availableSpots: number
  generatedSpots: number
  createdAt?: Date | string
  updatedAt?: Date | string
  charges?: Prisma.ChargeUncheckedCreateNestedManyWithoutInvoiceSummaryInput
}

export type InvoiceSummaryCreateOrConnectWithoutSubscriptionInput = {
  where: Prisma.InvoiceSummaryWhereUniqueInput
  create: Prisma.XOR<Prisma.InvoiceSummaryCreateWithoutSubscriptionInput, Prisma.InvoiceSummaryUncheckedCreateWithoutSubscriptionInput>
}

export type InvoiceSummaryCreateManySubscriptionInputEnvelope = {
  data: Prisma.InvoiceSummaryCreateManySubscriptionInput | Prisma.InvoiceSummaryCreateManySubscriptionInput[]
  skipDuplicates?: boolean
}

export type InvoiceSummaryUpsertWithWhereUniqueWithoutSubscriptionInput = {
  where: Prisma.InvoiceSummaryWhereUniqueInput
  update: Prisma.XOR<Prisma.InvoiceSummaryUpdateWithoutSubscriptionInput, Prisma.InvoiceSummaryUncheckedUpdateWithoutSubscriptionInput>
  create: Prisma.XOR<Prisma.InvoiceSummaryCreateWithoutSubscriptionInput, Prisma.InvoiceSummaryUncheckedCreateWithoutSubscriptionInput>
}

export type InvoiceSummaryUpdateWithWhereUniqueWithoutSubscriptionInput = {
  where: Prisma.InvoiceSummaryWhereUniqueInput
  data: Prisma.XOR<Prisma.InvoiceSummaryUpdateWithoutSubscriptionInput, Prisma.InvoiceSummaryUncheckedUpdateWithoutSubscriptionInput>
}

export type InvoiceSummaryUpdateManyWithWhereWithoutSubscriptionInput = {
  where: Prisma.InvoiceSummaryScalarWhereInput
  data: Prisma.XOR<Prisma.InvoiceSummaryUpdateManyMutationInput, Prisma.InvoiceSummaryUncheckedUpdateManyWithoutSubscriptionInput>
}

export type InvoiceSummaryScalarWhereInput = {
  AND?: Prisma.InvoiceSummaryScalarWhereInput | Prisma.InvoiceSummaryScalarWhereInput[]
  OR?: Prisma.InvoiceSummaryScalarWhereInput[]
  NOT?: Prisma.InvoiceSummaryScalarWhereInput | Prisma.InvoiceSummaryScalarWhereInput[]
  id?: Prisma.StringFilter<"InvoiceSummary"> | string
  fromAt?: Prisma.DateTimeFilter<"InvoiceSummary"> | Date | string
  toAt?: Prisma.DateTimeFilter<"InvoiceSummary"> | Date | string
  availableSpots?: Prisma.IntFilter<"InvoiceSummary"> | number
  generatedSpots?: Prisma.IntFilter<"InvoiceSummary"> | number
  createdAt?: Prisma.DateTimeFilter<"InvoiceSummary"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"InvoiceSummary"> | Date | string
  subscriptionId?: Prisma.StringFilter<"InvoiceSummary"> | string
}

export type InvoiceSummaryCreateWithoutChargesInput = {
  id?: string
  fromAt: Date | string
  toAt: Date | string
  availableSpots: number
  generatedSpots: number
  createdAt?: Date | string
  updatedAt?: Date | string
  subscription: Prisma.SubscriptionCreateNestedOneWithoutInvoicesInput
}

export type InvoiceSummaryUncheckedCreateWithoutChargesInput = {
  id?: string
  fromAt: Date | string
  toAt: Date | string
  availableSpots: number
  generatedSpots: number
  createdAt?: Date | string
  updatedAt?: Date | string
  subscriptionId: string
}

export type InvoiceSummaryCreateOrConnectWithoutChargesInput = {
  where: Prisma.InvoiceSummaryWhereUniqueInput
  create: Prisma.XOR<Prisma.InvoiceSummaryCreateWithoutChargesInput, Prisma.InvoiceSummaryUncheckedCreateWithoutChargesInput>
}

export type InvoiceSummaryUpsertWithoutChargesInput = {
  update: Prisma.XOR<Prisma.InvoiceSummaryUpdateWithoutChargesInput, Prisma.InvoiceSummaryUncheckedUpdateWithoutChargesInput>
  create: Prisma.XOR<Prisma.InvoiceSummaryCreateWithoutChargesInput, Prisma.InvoiceSummaryUncheckedCreateWithoutChargesInput>
  where?: Prisma.InvoiceSummaryWhereInput
}

export type InvoiceSummaryUpdateToOneWithWhereWithoutChargesInput = {
  where?: Prisma.InvoiceSummaryWhereInput
  data: Prisma.XOR<Prisma.InvoiceSummaryUpdateWithoutChargesInput, Prisma.InvoiceSummaryUncheckedUpdateWithoutChargesInput>
}

export type InvoiceSummaryUpdateWithoutChargesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fromAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  toAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  availableSpots?: Prisma.IntFieldUpdateOperationsInput | number
  generatedSpots?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  subscription?: Prisma.SubscriptionUpdateOneRequiredWithoutInvoicesNestedInput
}

export type InvoiceSummaryUncheckedUpdateWithoutChargesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fromAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  toAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  availableSpots?: Prisma.IntFieldUpdateOperationsInput | number
  generatedSpots?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  subscriptionId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type InvoiceSummaryCreateManySubscriptionInput = {
  id?: string
  fromAt: Date | string
  toAt: Date | string
  availableSpots: number
  generatedSpots: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type InvoiceSummaryUpdateWithoutSubscriptionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fromAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  toAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  availableSpots?: Prisma.IntFieldUpdateOperationsInput | number
  generatedSpots?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  charges?: Prisma.ChargeUpdateManyWithoutInvoiceSummaryNestedInput
}

export type InvoiceSummaryUncheckedUpdateWithoutSubscriptionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fromAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  toAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  availableSpots?: Prisma.IntFieldUpdateOperationsInput | number
  generatedSpots?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  charges?: Prisma.ChargeUncheckedUpdateManyWithoutInvoiceSummaryNestedInput
}

export type InvoiceSummaryUncheckedUpdateManyWithoutSubscriptionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fromAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  toAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  availableSpots?: Prisma.IntFieldUpdateOperationsInput | number
  generatedSpots?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type InvoiceSummaryCountOutputType
 */

export type InvoiceSummaryCountOutputType = {
  charges: number
}

export type InvoiceSummaryCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  charges?: boolean | InvoiceSummaryCountOutputTypeCountChargesArgs
}

/**
 * InvoiceSummaryCountOutputType without action
 */
export type InvoiceSummaryCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InvoiceSummaryCountOutputType
   */
  select?: Prisma.InvoiceSummaryCountOutputTypeSelect<ExtArgs> | null
}

/**
 * InvoiceSummaryCountOutputType without action
 */
export type InvoiceSummaryCountOutputTypeCountChargesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ChargeWhereInput
}


export type InvoiceSummarySelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  fromAt?: boolean
  toAt?: boolean
  availableSpots?: boolean
  generatedSpots?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  subscriptionId?: boolean
  subscription?: boolean | Prisma.SubscriptionDefaultArgs<ExtArgs>
  charges?: boolean | Prisma.InvoiceSummary$chargesArgs<ExtArgs>
  _count?: boolean | Prisma.InvoiceSummaryCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["invoiceSummary"]>

export type InvoiceSummarySelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  fromAt?: boolean
  toAt?: boolean
  availableSpots?: boolean
  generatedSpots?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  subscriptionId?: boolean
  subscription?: boolean | Prisma.SubscriptionDefaultArgs<ExtArgs>
}, ExtArgs["result"]["invoiceSummary"]>

export type InvoiceSummarySelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  fromAt?: boolean
  toAt?: boolean
  availableSpots?: boolean
  generatedSpots?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  subscriptionId?: boolean
  subscription?: boolean | Prisma.SubscriptionDefaultArgs<ExtArgs>
}, ExtArgs["result"]["invoiceSummary"]>

export type InvoiceSummarySelectScalar = {
  id?: boolean
  fromAt?: boolean
  toAt?: boolean
  availableSpots?: boolean
  generatedSpots?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  subscriptionId?: boolean
}

export type InvoiceSummaryOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "fromAt" | "toAt" | "availableSpots" | "generatedSpots" | "createdAt" | "updatedAt" | "subscriptionId", ExtArgs["result"]["invoiceSummary"]>
export type InvoiceSummaryInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  subscription?: boolean | Prisma.SubscriptionDefaultArgs<ExtArgs>
  charges?: boolean | Prisma.InvoiceSummary$chargesArgs<ExtArgs>
  _count?: boolean | Prisma.InvoiceSummaryCountOutputTypeDefaultArgs<ExtArgs>
}
export type InvoiceSummaryIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  subscription?: boolean | Prisma.SubscriptionDefaultArgs<ExtArgs>
}
export type InvoiceSummaryIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  subscription?: boolean | Prisma.SubscriptionDefaultArgs<ExtArgs>
}

export type $InvoiceSummaryPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "InvoiceSummary"
  objects: {
    subscription: Prisma.$SubscriptionPayload<ExtArgs>
    charges: Prisma.$ChargePayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    fromAt: Date
    toAt: Date
    availableSpots: number
    generatedSpots: number
    createdAt: Date
    updatedAt: Date
    subscriptionId: string
  }, ExtArgs["result"]["invoiceSummary"]>
  composites: {}
}

export type InvoiceSummaryGetPayload<S extends boolean | null | undefined | InvoiceSummaryDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$InvoiceSummaryPayload, S>

export type InvoiceSummaryCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<InvoiceSummaryFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: InvoiceSummaryCountAggregateInputType | true
  }

export interface InvoiceSummaryDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['InvoiceSummary'], meta: { name: 'InvoiceSummary' } }
  /**
   * Find zero or one InvoiceSummary that matches the filter.
   * @param {InvoiceSummaryFindUniqueArgs} args - Arguments to find a InvoiceSummary
   * @example
   * // Get one InvoiceSummary
   * const invoiceSummary = await prisma.invoiceSummary.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends InvoiceSummaryFindUniqueArgs>(args: Prisma.SelectSubset<T, InvoiceSummaryFindUniqueArgs<ExtArgs>>): Prisma.Prisma__InvoiceSummaryClient<runtime.Types.Result.GetResult<Prisma.$InvoiceSummaryPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one InvoiceSummary that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {InvoiceSummaryFindUniqueOrThrowArgs} args - Arguments to find a InvoiceSummary
   * @example
   * // Get one InvoiceSummary
   * const invoiceSummary = await prisma.invoiceSummary.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends InvoiceSummaryFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, InvoiceSummaryFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__InvoiceSummaryClient<runtime.Types.Result.GetResult<Prisma.$InvoiceSummaryPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first InvoiceSummary that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InvoiceSummaryFindFirstArgs} args - Arguments to find a InvoiceSummary
   * @example
   * // Get one InvoiceSummary
   * const invoiceSummary = await prisma.invoiceSummary.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends InvoiceSummaryFindFirstArgs>(args?: Prisma.SelectSubset<T, InvoiceSummaryFindFirstArgs<ExtArgs>>): Prisma.Prisma__InvoiceSummaryClient<runtime.Types.Result.GetResult<Prisma.$InvoiceSummaryPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first InvoiceSummary that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InvoiceSummaryFindFirstOrThrowArgs} args - Arguments to find a InvoiceSummary
   * @example
   * // Get one InvoiceSummary
   * const invoiceSummary = await prisma.invoiceSummary.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends InvoiceSummaryFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, InvoiceSummaryFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__InvoiceSummaryClient<runtime.Types.Result.GetResult<Prisma.$InvoiceSummaryPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more InvoiceSummaries that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InvoiceSummaryFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all InvoiceSummaries
   * const invoiceSummaries = await prisma.invoiceSummary.findMany()
   * 
   * // Get first 10 InvoiceSummaries
   * const invoiceSummaries = await prisma.invoiceSummary.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const invoiceSummaryWithIdOnly = await prisma.invoiceSummary.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends InvoiceSummaryFindManyArgs>(args?: Prisma.SelectSubset<T, InvoiceSummaryFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$InvoiceSummaryPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a InvoiceSummary.
   * @param {InvoiceSummaryCreateArgs} args - Arguments to create a InvoiceSummary.
   * @example
   * // Create one InvoiceSummary
   * const InvoiceSummary = await prisma.invoiceSummary.create({
   *   data: {
   *     // ... data to create a InvoiceSummary
   *   }
   * })
   * 
   */
  create<T extends InvoiceSummaryCreateArgs>(args: Prisma.SelectSubset<T, InvoiceSummaryCreateArgs<ExtArgs>>): Prisma.Prisma__InvoiceSummaryClient<runtime.Types.Result.GetResult<Prisma.$InvoiceSummaryPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many InvoiceSummaries.
   * @param {InvoiceSummaryCreateManyArgs} args - Arguments to create many InvoiceSummaries.
   * @example
   * // Create many InvoiceSummaries
   * const invoiceSummary = await prisma.invoiceSummary.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends InvoiceSummaryCreateManyArgs>(args?: Prisma.SelectSubset<T, InvoiceSummaryCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many InvoiceSummaries and returns the data saved in the database.
   * @param {InvoiceSummaryCreateManyAndReturnArgs} args - Arguments to create many InvoiceSummaries.
   * @example
   * // Create many InvoiceSummaries
   * const invoiceSummary = await prisma.invoiceSummary.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many InvoiceSummaries and only return the `id`
   * const invoiceSummaryWithIdOnly = await prisma.invoiceSummary.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends InvoiceSummaryCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, InvoiceSummaryCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$InvoiceSummaryPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a InvoiceSummary.
   * @param {InvoiceSummaryDeleteArgs} args - Arguments to delete one InvoiceSummary.
   * @example
   * // Delete one InvoiceSummary
   * const InvoiceSummary = await prisma.invoiceSummary.delete({
   *   where: {
   *     // ... filter to delete one InvoiceSummary
   *   }
   * })
   * 
   */
  delete<T extends InvoiceSummaryDeleteArgs>(args: Prisma.SelectSubset<T, InvoiceSummaryDeleteArgs<ExtArgs>>): Prisma.Prisma__InvoiceSummaryClient<runtime.Types.Result.GetResult<Prisma.$InvoiceSummaryPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one InvoiceSummary.
   * @param {InvoiceSummaryUpdateArgs} args - Arguments to update one InvoiceSummary.
   * @example
   * // Update one InvoiceSummary
   * const invoiceSummary = await prisma.invoiceSummary.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends InvoiceSummaryUpdateArgs>(args: Prisma.SelectSubset<T, InvoiceSummaryUpdateArgs<ExtArgs>>): Prisma.Prisma__InvoiceSummaryClient<runtime.Types.Result.GetResult<Prisma.$InvoiceSummaryPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more InvoiceSummaries.
   * @param {InvoiceSummaryDeleteManyArgs} args - Arguments to filter InvoiceSummaries to delete.
   * @example
   * // Delete a few InvoiceSummaries
   * const { count } = await prisma.invoiceSummary.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends InvoiceSummaryDeleteManyArgs>(args?: Prisma.SelectSubset<T, InvoiceSummaryDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more InvoiceSummaries.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InvoiceSummaryUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many InvoiceSummaries
   * const invoiceSummary = await prisma.invoiceSummary.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends InvoiceSummaryUpdateManyArgs>(args: Prisma.SelectSubset<T, InvoiceSummaryUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more InvoiceSummaries and returns the data updated in the database.
   * @param {InvoiceSummaryUpdateManyAndReturnArgs} args - Arguments to update many InvoiceSummaries.
   * @example
   * // Update many InvoiceSummaries
   * const invoiceSummary = await prisma.invoiceSummary.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more InvoiceSummaries and only return the `id`
   * const invoiceSummaryWithIdOnly = await prisma.invoiceSummary.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends InvoiceSummaryUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, InvoiceSummaryUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$InvoiceSummaryPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one InvoiceSummary.
   * @param {InvoiceSummaryUpsertArgs} args - Arguments to update or create a InvoiceSummary.
   * @example
   * // Update or create a InvoiceSummary
   * const invoiceSummary = await prisma.invoiceSummary.upsert({
   *   create: {
   *     // ... data to create a InvoiceSummary
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the InvoiceSummary we want to update
   *   }
   * })
   */
  upsert<T extends InvoiceSummaryUpsertArgs>(args: Prisma.SelectSubset<T, InvoiceSummaryUpsertArgs<ExtArgs>>): Prisma.Prisma__InvoiceSummaryClient<runtime.Types.Result.GetResult<Prisma.$InvoiceSummaryPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of InvoiceSummaries.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InvoiceSummaryCountArgs} args - Arguments to filter InvoiceSummaries to count.
   * @example
   * // Count the number of InvoiceSummaries
   * const count = await prisma.invoiceSummary.count({
   *   where: {
   *     // ... the filter for the InvoiceSummaries we want to count
   *   }
   * })
  **/
  count<T extends InvoiceSummaryCountArgs>(
    args?: Prisma.Subset<T, InvoiceSummaryCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], InvoiceSummaryCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a InvoiceSummary.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InvoiceSummaryAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends InvoiceSummaryAggregateArgs>(args: Prisma.Subset<T, InvoiceSummaryAggregateArgs>): Prisma.PrismaPromise<GetInvoiceSummaryAggregateType<T>>

  /**
   * Group by InvoiceSummary.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InvoiceSummaryGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends InvoiceSummaryGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: InvoiceSummaryGroupByArgs['orderBy'] }
      : { orderBy?: InvoiceSummaryGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, InvoiceSummaryGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetInvoiceSummaryGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the InvoiceSummary model
 */
readonly fields: InvoiceSummaryFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for InvoiceSummary.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__InvoiceSummaryClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  subscription<T extends Prisma.SubscriptionDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.SubscriptionDefaultArgs<ExtArgs>>): Prisma.Prisma__SubscriptionClient<runtime.Types.Result.GetResult<Prisma.$SubscriptionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  charges<T extends Prisma.InvoiceSummary$chargesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.InvoiceSummary$chargesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ChargePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the InvoiceSummary model
 */
export interface InvoiceSummaryFieldRefs {
  readonly id: Prisma.FieldRef<"InvoiceSummary", 'String'>
  readonly fromAt: Prisma.FieldRef<"InvoiceSummary", 'DateTime'>
  readonly toAt: Prisma.FieldRef<"InvoiceSummary", 'DateTime'>
  readonly availableSpots: Prisma.FieldRef<"InvoiceSummary", 'Int'>
  readonly generatedSpots: Prisma.FieldRef<"InvoiceSummary", 'Int'>
  readonly createdAt: Prisma.FieldRef<"InvoiceSummary", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"InvoiceSummary", 'DateTime'>
  readonly subscriptionId: Prisma.FieldRef<"InvoiceSummary", 'String'>
}
    

// Custom InputTypes
/**
 * InvoiceSummary findUnique
 */
export type InvoiceSummaryFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InvoiceSummary
   */
  select?: Prisma.InvoiceSummarySelect<ExtArgs> | null
  /**
   * Omit specific fields from the InvoiceSummary
   */
  omit?: Prisma.InvoiceSummaryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InvoiceSummaryInclude<ExtArgs> | null
  /**
   * Filter, which InvoiceSummary to fetch.
   */
  where: Prisma.InvoiceSummaryWhereUniqueInput
}

/**
 * InvoiceSummary findUniqueOrThrow
 */
export type InvoiceSummaryFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InvoiceSummary
   */
  select?: Prisma.InvoiceSummarySelect<ExtArgs> | null
  /**
   * Omit specific fields from the InvoiceSummary
   */
  omit?: Prisma.InvoiceSummaryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InvoiceSummaryInclude<ExtArgs> | null
  /**
   * Filter, which InvoiceSummary to fetch.
   */
  where: Prisma.InvoiceSummaryWhereUniqueInput
}

/**
 * InvoiceSummary findFirst
 */
export type InvoiceSummaryFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InvoiceSummary
   */
  select?: Prisma.InvoiceSummarySelect<ExtArgs> | null
  /**
   * Omit specific fields from the InvoiceSummary
   */
  omit?: Prisma.InvoiceSummaryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InvoiceSummaryInclude<ExtArgs> | null
  /**
   * Filter, which InvoiceSummary to fetch.
   */
  where?: Prisma.InvoiceSummaryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of InvoiceSummaries to fetch.
   */
  orderBy?: Prisma.InvoiceSummaryOrderByWithRelationInput | Prisma.InvoiceSummaryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for InvoiceSummaries.
   */
  cursor?: Prisma.InvoiceSummaryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` InvoiceSummaries from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` InvoiceSummaries.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of InvoiceSummaries.
   */
  distinct?: Prisma.InvoiceSummaryScalarFieldEnum | Prisma.InvoiceSummaryScalarFieldEnum[]
}

/**
 * InvoiceSummary findFirstOrThrow
 */
export type InvoiceSummaryFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InvoiceSummary
   */
  select?: Prisma.InvoiceSummarySelect<ExtArgs> | null
  /**
   * Omit specific fields from the InvoiceSummary
   */
  omit?: Prisma.InvoiceSummaryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InvoiceSummaryInclude<ExtArgs> | null
  /**
   * Filter, which InvoiceSummary to fetch.
   */
  where?: Prisma.InvoiceSummaryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of InvoiceSummaries to fetch.
   */
  orderBy?: Prisma.InvoiceSummaryOrderByWithRelationInput | Prisma.InvoiceSummaryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for InvoiceSummaries.
   */
  cursor?: Prisma.InvoiceSummaryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` InvoiceSummaries from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` InvoiceSummaries.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of InvoiceSummaries.
   */
  distinct?: Prisma.InvoiceSummaryScalarFieldEnum | Prisma.InvoiceSummaryScalarFieldEnum[]
}

/**
 * InvoiceSummary findMany
 */
export type InvoiceSummaryFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InvoiceSummary
   */
  select?: Prisma.InvoiceSummarySelect<ExtArgs> | null
  /**
   * Omit specific fields from the InvoiceSummary
   */
  omit?: Prisma.InvoiceSummaryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InvoiceSummaryInclude<ExtArgs> | null
  /**
   * Filter, which InvoiceSummaries to fetch.
   */
  where?: Prisma.InvoiceSummaryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of InvoiceSummaries to fetch.
   */
  orderBy?: Prisma.InvoiceSummaryOrderByWithRelationInput | Prisma.InvoiceSummaryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing InvoiceSummaries.
   */
  cursor?: Prisma.InvoiceSummaryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` InvoiceSummaries from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` InvoiceSummaries.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of InvoiceSummaries.
   */
  distinct?: Prisma.InvoiceSummaryScalarFieldEnum | Prisma.InvoiceSummaryScalarFieldEnum[]
}

/**
 * InvoiceSummary create
 */
export type InvoiceSummaryCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InvoiceSummary
   */
  select?: Prisma.InvoiceSummarySelect<ExtArgs> | null
  /**
   * Omit specific fields from the InvoiceSummary
   */
  omit?: Prisma.InvoiceSummaryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InvoiceSummaryInclude<ExtArgs> | null
  /**
   * The data needed to create a InvoiceSummary.
   */
  data: Prisma.XOR<Prisma.InvoiceSummaryCreateInput, Prisma.InvoiceSummaryUncheckedCreateInput>
}

/**
 * InvoiceSummary createMany
 */
export type InvoiceSummaryCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many InvoiceSummaries.
   */
  data: Prisma.InvoiceSummaryCreateManyInput | Prisma.InvoiceSummaryCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * InvoiceSummary createManyAndReturn
 */
export type InvoiceSummaryCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InvoiceSummary
   */
  select?: Prisma.InvoiceSummarySelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the InvoiceSummary
   */
  omit?: Prisma.InvoiceSummaryOmit<ExtArgs> | null
  /**
   * The data used to create many InvoiceSummaries.
   */
  data: Prisma.InvoiceSummaryCreateManyInput | Prisma.InvoiceSummaryCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InvoiceSummaryIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * InvoiceSummary update
 */
export type InvoiceSummaryUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InvoiceSummary
   */
  select?: Prisma.InvoiceSummarySelect<ExtArgs> | null
  /**
   * Omit specific fields from the InvoiceSummary
   */
  omit?: Prisma.InvoiceSummaryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InvoiceSummaryInclude<ExtArgs> | null
  /**
   * The data needed to update a InvoiceSummary.
   */
  data: Prisma.XOR<Prisma.InvoiceSummaryUpdateInput, Prisma.InvoiceSummaryUncheckedUpdateInput>
  /**
   * Choose, which InvoiceSummary to update.
   */
  where: Prisma.InvoiceSummaryWhereUniqueInput
}

/**
 * InvoiceSummary updateMany
 */
export type InvoiceSummaryUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update InvoiceSummaries.
   */
  data: Prisma.XOR<Prisma.InvoiceSummaryUpdateManyMutationInput, Prisma.InvoiceSummaryUncheckedUpdateManyInput>
  /**
   * Filter which InvoiceSummaries to update
   */
  where?: Prisma.InvoiceSummaryWhereInput
  /**
   * Limit how many InvoiceSummaries to update.
   */
  limit?: number
}

/**
 * InvoiceSummary updateManyAndReturn
 */
export type InvoiceSummaryUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InvoiceSummary
   */
  select?: Prisma.InvoiceSummarySelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the InvoiceSummary
   */
  omit?: Prisma.InvoiceSummaryOmit<ExtArgs> | null
  /**
   * The data used to update InvoiceSummaries.
   */
  data: Prisma.XOR<Prisma.InvoiceSummaryUpdateManyMutationInput, Prisma.InvoiceSummaryUncheckedUpdateManyInput>
  /**
   * Filter which InvoiceSummaries to update
   */
  where?: Prisma.InvoiceSummaryWhereInput
  /**
   * Limit how many InvoiceSummaries to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InvoiceSummaryIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * InvoiceSummary upsert
 */
export type InvoiceSummaryUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InvoiceSummary
   */
  select?: Prisma.InvoiceSummarySelect<ExtArgs> | null
  /**
   * Omit specific fields from the InvoiceSummary
   */
  omit?: Prisma.InvoiceSummaryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InvoiceSummaryInclude<ExtArgs> | null
  /**
   * The filter to search for the InvoiceSummary to update in case it exists.
   */
  where: Prisma.InvoiceSummaryWhereUniqueInput
  /**
   * In case the InvoiceSummary found by the `where` argument doesn't exist, create a new InvoiceSummary with this data.
   */
  create: Prisma.XOR<Prisma.InvoiceSummaryCreateInput, Prisma.InvoiceSummaryUncheckedCreateInput>
  /**
   * In case the InvoiceSummary was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.InvoiceSummaryUpdateInput, Prisma.InvoiceSummaryUncheckedUpdateInput>
}

/**
 * InvoiceSummary delete
 */
export type InvoiceSummaryDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InvoiceSummary
   */
  select?: Prisma.InvoiceSummarySelect<ExtArgs> | null
  /**
   * Omit specific fields from the InvoiceSummary
   */
  omit?: Prisma.InvoiceSummaryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InvoiceSummaryInclude<ExtArgs> | null
  /**
   * Filter which InvoiceSummary to delete.
   */
  where: Prisma.InvoiceSummaryWhereUniqueInput
}

/**
 * InvoiceSummary deleteMany
 */
export type InvoiceSummaryDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which InvoiceSummaries to delete
   */
  where?: Prisma.InvoiceSummaryWhereInput
  /**
   * Limit how many InvoiceSummaries to delete.
   */
  limit?: number
}

/**
 * InvoiceSummary.charges
 */
export type InvoiceSummary$chargesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Charge
   */
  select?: Prisma.ChargeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Charge
   */
  omit?: Prisma.ChargeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ChargeInclude<ExtArgs> | null
  where?: Prisma.ChargeWhereInput
  orderBy?: Prisma.ChargeOrderByWithRelationInput | Prisma.ChargeOrderByWithRelationInput[]
  cursor?: Prisma.ChargeWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ChargeScalarFieldEnum | Prisma.ChargeScalarFieldEnum[]
}

/**
 * InvoiceSummary without action
 */
export type InvoiceSummaryDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InvoiceSummary
   */
  select?: Prisma.InvoiceSummarySelect<ExtArgs> | null
  /**
   * Omit specific fields from the InvoiceSummary
   */
  omit?: Prisma.InvoiceSummaryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InvoiceSummaryInclude<ExtArgs> | null
}
