
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `SpotCost` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model SpotCost
 * 
 */
export type SpotCostModel = runtime.Types.Result.DefaultSelection<Prisma.$SpotCostPayload>

export type AggregateSpotCost = {
  _count: SpotCostCountAggregateOutputType | null
  _avg: SpotCostAvgAggregateOutputType | null
  _sum: SpotCostSumAggregateOutputType | null
  _min: SpotCostMinAggregateOutputType | null
  _max: SpotCostMaxAggregateOutputType | null
}

export type SpotCostAvgAggregateOutputType = {
  costCents: number | null
}

export type SpotCostSumAggregateOutputType = {
  costCents: number | null
}

export type SpotCostMinAggregateOutputType = {
  id: string | null
  provider: $Enums.CostProvider | null
  service: $Enums.CostService | null
  costCents: number | null
  spotId: string | null
}

export type SpotCostMaxAggregateOutputType = {
  id: string | null
  provider: $Enums.CostProvider | null
  service: $Enums.CostService | null
  costCents: number | null
  spotId: string | null
}

export type SpotCostCountAggregateOutputType = {
  id: number
  provider: number
  service: number
  costCents: number
  metadata: number
  spotId: number
  _all: number
}


export type SpotCostAvgAggregateInputType = {
  costCents?: true
}

export type SpotCostSumAggregateInputType = {
  costCents?: true
}

export type SpotCostMinAggregateInputType = {
  id?: true
  provider?: true
  service?: true
  costCents?: true
  spotId?: true
}

export type SpotCostMaxAggregateInputType = {
  id?: true
  provider?: true
  service?: true
  costCents?: true
  spotId?: true
}

export type SpotCostCountAggregateInputType = {
  id?: true
  provider?: true
  service?: true
  costCents?: true
  metadata?: true
  spotId?: true
  _all?: true
}

export type SpotCostAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which SpotCost to aggregate.
   */
  where?: Prisma.SpotCostWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SpotCosts to fetch.
   */
  orderBy?: Prisma.SpotCostOrderByWithRelationInput | Prisma.SpotCostOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.SpotCostWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SpotCosts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SpotCosts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned SpotCosts
  **/
  _count?: true | SpotCostCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: SpotCostAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: SpotCostSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: SpotCostMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: SpotCostMaxAggregateInputType
}

export type GetSpotCostAggregateType<T extends SpotCostAggregateArgs> = {
      [P in keyof T & keyof AggregateSpotCost]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateSpotCost[P]>
    : Prisma.GetScalarType<T[P], AggregateSpotCost[P]>
}




export type SpotCostGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.SpotCostWhereInput
  orderBy?: Prisma.SpotCostOrderByWithAggregationInput | Prisma.SpotCostOrderByWithAggregationInput[]
  by: Prisma.SpotCostScalarFieldEnum[] | Prisma.SpotCostScalarFieldEnum
  having?: Prisma.SpotCostScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: SpotCostCountAggregateInputType | true
  _avg?: SpotCostAvgAggregateInputType
  _sum?: SpotCostSumAggregateInputType
  _min?: SpotCostMinAggregateInputType
  _max?: SpotCostMaxAggregateInputType
}

export type SpotCostGroupByOutputType = {
  id: string
  provider: $Enums.CostProvider
  service: $Enums.CostService
  costCents: number
  metadata: runtime.JsonValue | null
  spotId: string
  _count: SpotCostCountAggregateOutputType | null
  _avg: SpotCostAvgAggregateOutputType | null
  _sum: SpotCostSumAggregateOutputType | null
  _min: SpotCostMinAggregateOutputType | null
  _max: SpotCostMaxAggregateOutputType | null
}

export type GetSpotCostGroupByPayload<T extends SpotCostGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<SpotCostGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof SpotCostGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], SpotCostGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], SpotCostGroupByOutputType[P]>
      }
    >
  >



export type SpotCostWhereInput = {
  AND?: Prisma.SpotCostWhereInput | Prisma.SpotCostWhereInput[]
  OR?: Prisma.SpotCostWhereInput[]
  NOT?: Prisma.SpotCostWhereInput | Prisma.SpotCostWhereInput[]
  id?: Prisma.StringFilter<"SpotCost"> | string
  provider?: Prisma.EnumCostProviderFilter<"SpotCost"> | $Enums.CostProvider
  service?: Prisma.EnumCostServiceFilter<"SpotCost"> | $Enums.CostService
  costCents?: Prisma.IntFilter<"SpotCost"> | number
  metadata?: Prisma.JsonNullableFilter<"SpotCost">
  spotId?: Prisma.StringFilter<"SpotCost"> | string
  spot?: Prisma.XOR<Prisma.SpotScalarRelationFilter, Prisma.SpotWhereInput>
}

export type SpotCostOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  provider?: Prisma.SortOrder
  service?: Prisma.SortOrder
  costCents?: Prisma.SortOrder
  metadata?: Prisma.SortOrderInput | Prisma.SortOrder
  spotId?: Prisma.SortOrder
  spot?: Prisma.SpotOrderByWithRelationInput
}

export type SpotCostWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  spotId?: string
  AND?: Prisma.SpotCostWhereInput | Prisma.SpotCostWhereInput[]
  OR?: Prisma.SpotCostWhereInput[]
  NOT?: Prisma.SpotCostWhereInput | Prisma.SpotCostWhereInput[]
  provider?: Prisma.EnumCostProviderFilter<"SpotCost"> | $Enums.CostProvider
  service?: Prisma.EnumCostServiceFilter<"SpotCost"> | $Enums.CostService
  costCents?: Prisma.IntFilter<"SpotCost"> | number
  metadata?: Prisma.JsonNullableFilter<"SpotCost">
  spot?: Prisma.XOR<Prisma.SpotScalarRelationFilter, Prisma.SpotWhereInput>
}, "id" | "spotId">

export type SpotCostOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  provider?: Prisma.SortOrder
  service?: Prisma.SortOrder
  costCents?: Prisma.SortOrder
  metadata?: Prisma.SortOrderInput | Prisma.SortOrder
  spotId?: Prisma.SortOrder
  _count?: Prisma.SpotCostCountOrderByAggregateInput
  _avg?: Prisma.SpotCostAvgOrderByAggregateInput
  _max?: Prisma.SpotCostMaxOrderByAggregateInput
  _min?: Prisma.SpotCostMinOrderByAggregateInput
  _sum?: Prisma.SpotCostSumOrderByAggregateInput
}

export type SpotCostScalarWhereWithAggregatesInput = {
  AND?: Prisma.SpotCostScalarWhereWithAggregatesInput | Prisma.SpotCostScalarWhereWithAggregatesInput[]
  OR?: Prisma.SpotCostScalarWhereWithAggregatesInput[]
  NOT?: Prisma.SpotCostScalarWhereWithAggregatesInput | Prisma.SpotCostScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"SpotCost"> | string
  provider?: Prisma.EnumCostProviderWithAggregatesFilter<"SpotCost"> | $Enums.CostProvider
  service?: Prisma.EnumCostServiceWithAggregatesFilter<"SpotCost"> | $Enums.CostService
  costCents?: Prisma.IntWithAggregatesFilter<"SpotCost"> | number
  metadata?: Prisma.JsonNullableWithAggregatesFilter<"SpotCost">
  spotId?: Prisma.StringWithAggregatesFilter<"SpotCost"> | string
}

export type SpotCostCreateInput = {
  id?: string
  provider: $Enums.CostProvider
  service: $Enums.CostService
  costCents: number
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  spot: Prisma.SpotCreateNestedOneWithoutCostsInput
}

export type SpotCostUncheckedCreateInput = {
  id?: string
  provider: $Enums.CostProvider
  service: $Enums.CostService
  costCents: number
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  spotId: string
}

export type SpotCostUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  provider?: Prisma.EnumCostProviderFieldUpdateOperationsInput | $Enums.CostProvider
  service?: Prisma.EnumCostServiceFieldUpdateOperationsInput | $Enums.CostService
  costCents?: Prisma.IntFieldUpdateOperationsInput | number
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  spot?: Prisma.SpotUpdateOneRequiredWithoutCostsNestedInput
}

export type SpotCostUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  provider?: Prisma.EnumCostProviderFieldUpdateOperationsInput | $Enums.CostProvider
  service?: Prisma.EnumCostServiceFieldUpdateOperationsInput | $Enums.CostService
  costCents?: Prisma.IntFieldUpdateOperationsInput | number
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  spotId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type SpotCostCreateManyInput = {
  id?: string
  provider: $Enums.CostProvider
  service: $Enums.CostService
  costCents: number
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  spotId: string
}

export type SpotCostUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  provider?: Prisma.EnumCostProviderFieldUpdateOperationsInput | $Enums.CostProvider
  service?: Prisma.EnumCostServiceFieldUpdateOperationsInput | $Enums.CostService
  costCents?: Prisma.IntFieldUpdateOperationsInput | number
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
}

export type SpotCostUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  provider?: Prisma.EnumCostProviderFieldUpdateOperationsInput | $Enums.CostProvider
  service?: Prisma.EnumCostServiceFieldUpdateOperationsInput | $Enums.CostService
  costCents?: Prisma.IntFieldUpdateOperationsInput | number
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  spotId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type SpotCostListRelationFilter = {
  every?: Prisma.SpotCostWhereInput
  some?: Prisma.SpotCostWhereInput
  none?: Prisma.SpotCostWhereInput
}

export type SpotCostOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type SpotCostCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  provider?: Prisma.SortOrder
  service?: Prisma.SortOrder
  costCents?: Prisma.SortOrder
  metadata?: Prisma.SortOrder
  spotId?: Prisma.SortOrder
}

export type SpotCostAvgOrderByAggregateInput = {
  costCents?: Prisma.SortOrder
}

export type SpotCostMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  provider?: Prisma.SortOrder
  service?: Prisma.SortOrder
  costCents?: Prisma.SortOrder
  spotId?: Prisma.SortOrder
}

export type SpotCostMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  provider?: Prisma.SortOrder
  service?: Prisma.SortOrder
  costCents?: Prisma.SortOrder
  spotId?: Prisma.SortOrder
}

export type SpotCostSumOrderByAggregateInput = {
  costCents?: Prisma.SortOrder
}

export type SpotCostCreateNestedManyWithoutSpotInput = {
  create?: Prisma.XOR<Prisma.SpotCostCreateWithoutSpotInput, Prisma.SpotCostUncheckedCreateWithoutSpotInput> | Prisma.SpotCostCreateWithoutSpotInput[] | Prisma.SpotCostUncheckedCreateWithoutSpotInput[]
  connectOrCreate?: Prisma.SpotCostCreateOrConnectWithoutSpotInput | Prisma.SpotCostCreateOrConnectWithoutSpotInput[]
  createMany?: Prisma.SpotCostCreateManySpotInputEnvelope
  connect?: Prisma.SpotCostWhereUniqueInput | Prisma.SpotCostWhereUniqueInput[]
}

export type SpotCostUncheckedCreateNestedManyWithoutSpotInput = {
  create?: Prisma.XOR<Prisma.SpotCostCreateWithoutSpotInput, Prisma.SpotCostUncheckedCreateWithoutSpotInput> | Prisma.SpotCostCreateWithoutSpotInput[] | Prisma.SpotCostUncheckedCreateWithoutSpotInput[]
  connectOrCreate?: Prisma.SpotCostCreateOrConnectWithoutSpotInput | Prisma.SpotCostCreateOrConnectWithoutSpotInput[]
  createMany?: Prisma.SpotCostCreateManySpotInputEnvelope
  connect?: Prisma.SpotCostWhereUniqueInput | Prisma.SpotCostWhereUniqueInput[]
}

export type SpotCostUpdateManyWithoutSpotNestedInput = {
  create?: Prisma.XOR<Prisma.SpotCostCreateWithoutSpotInput, Prisma.SpotCostUncheckedCreateWithoutSpotInput> | Prisma.SpotCostCreateWithoutSpotInput[] | Prisma.SpotCostUncheckedCreateWithoutSpotInput[]
  connectOrCreate?: Prisma.SpotCostCreateOrConnectWithoutSpotInput | Prisma.SpotCostCreateOrConnectWithoutSpotInput[]
  upsert?: Prisma.SpotCostUpsertWithWhereUniqueWithoutSpotInput | Prisma.SpotCostUpsertWithWhereUniqueWithoutSpotInput[]
  createMany?: Prisma.SpotCostCreateManySpotInputEnvelope
  set?: Prisma.SpotCostWhereUniqueInput | Prisma.SpotCostWhereUniqueInput[]
  disconnect?: Prisma.SpotCostWhereUniqueInput | Prisma.SpotCostWhereUniqueInput[]
  delete?: Prisma.SpotCostWhereUniqueInput | Prisma.SpotCostWhereUniqueInput[]
  connect?: Prisma.SpotCostWhereUniqueInput | Prisma.SpotCostWhereUniqueInput[]
  update?: Prisma.SpotCostUpdateWithWhereUniqueWithoutSpotInput | Prisma.SpotCostUpdateWithWhereUniqueWithoutSpotInput[]
  updateMany?: Prisma.SpotCostUpdateManyWithWhereWithoutSpotInput | Prisma.SpotCostUpdateManyWithWhereWithoutSpotInput[]
  deleteMany?: Prisma.SpotCostScalarWhereInput | Prisma.SpotCostScalarWhereInput[]
}

export type SpotCostUncheckedUpdateManyWithoutSpotNestedInput = {
  create?: Prisma.XOR<Prisma.SpotCostCreateWithoutSpotInput, Prisma.SpotCostUncheckedCreateWithoutSpotInput> | Prisma.SpotCostCreateWithoutSpotInput[] | Prisma.SpotCostUncheckedCreateWithoutSpotInput[]
  connectOrCreate?: Prisma.SpotCostCreateOrConnectWithoutSpotInput | Prisma.SpotCostCreateOrConnectWithoutSpotInput[]
  upsert?: Prisma.SpotCostUpsertWithWhereUniqueWithoutSpotInput | Prisma.SpotCostUpsertWithWhereUniqueWithoutSpotInput[]
  createMany?: Prisma.SpotCostCreateManySpotInputEnvelope
  set?: Prisma.SpotCostWhereUniqueInput | Prisma.SpotCostWhereUniqueInput[]
  disconnect?: Prisma.SpotCostWhereUniqueInput | Prisma.SpotCostWhereUniqueInput[]
  delete?: Prisma.SpotCostWhereUniqueInput | Prisma.SpotCostWhereUniqueInput[]
  connect?: Prisma.SpotCostWhereUniqueInput | Prisma.SpotCostWhereUniqueInput[]
  update?: Prisma.SpotCostUpdateWithWhereUniqueWithoutSpotInput | Prisma.SpotCostUpdateWithWhereUniqueWithoutSpotInput[]
  updateMany?: Prisma.SpotCostUpdateManyWithWhereWithoutSpotInput | Prisma.SpotCostUpdateManyWithWhereWithoutSpotInput[]
  deleteMany?: Prisma.SpotCostScalarWhereInput | Prisma.SpotCostScalarWhereInput[]
}

export type EnumCostProviderFieldUpdateOperationsInput = {
  set?: $Enums.CostProvider
}

export type EnumCostServiceFieldUpdateOperationsInput = {
  set?: $Enums.CostService
}

export type SpotCostCreateWithoutSpotInput = {
  id?: string
  provider: $Enums.CostProvider
  service: $Enums.CostService
  costCents: number
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
}

export type SpotCostUncheckedCreateWithoutSpotInput = {
  id?: string
  provider: $Enums.CostProvider
  service: $Enums.CostService
  costCents: number
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
}

export type SpotCostCreateOrConnectWithoutSpotInput = {
  where: Prisma.SpotCostWhereUniqueInput
  create: Prisma.XOR<Prisma.SpotCostCreateWithoutSpotInput, Prisma.SpotCostUncheckedCreateWithoutSpotInput>
}

export type SpotCostCreateManySpotInputEnvelope = {
  data: Prisma.SpotCostCreateManySpotInput | Prisma.SpotCostCreateManySpotInput[]
  skipDuplicates?: boolean
}

export type SpotCostUpsertWithWhereUniqueWithoutSpotInput = {
  where: Prisma.SpotCostWhereUniqueInput
  update: Prisma.XOR<Prisma.SpotCostUpdateWithoutSpotInput, Prisma.SpotCostUncheckedUpdateWithoutSpotInput>
  create: Prisma.XOR<Prisma.SpotCostCreateWithoutSpotInput, Prisma.SpotCostUncheckedCreateWithoutSpotInput>
}

export type SpotCostUpdateWithWhereUniqueWithoutSpotInput = {
  where: Prisma.SpotCostWhereUniqueInput
  data: Prisma.XOR<Prisma.SpotCostUpdateWithoutSpotInput, Prisma.SpotCostUncheckedUpdateWithoutSpotInput>
}

export type SpotCostUpdateManyWithWhereWithoutSpotInput = {
  where: Prisma.SpotCostScalarWhereInput
  data: Prisma.XOR<Prisma.SpotCostUpdateManyMutationInput, Prisma.SpotCostUncheckedUpdateManyWithoutSpotInput>
}

export type SpotCostScalarWhereInput = {
  AND?: Prisma.SpotCostScalarWhereInput | Prisma.SpotCostScalarWhereInput[]
  OR?: Prisma.SpotCostScalarWhereInput[]
  NOT?: Prisma.SpotCostScalarWhereInput | Prisma.SpotCostScalarWhereInput[]
  id?: Prisma.StringFilter<"SpotCost"> | string
  provider?: Prisma.EnumCostProviderFilter<"SpotCost"> | $Enums.CostProvider
  service?: Prisma.EnumCostServiceFilter<"SpotCost"> | $Enums.CostService
  costCents?: Prisma.IntFilter<"SpotCost"> | number
  metadata?: Prisma.JsonNullableFilter<"SpotCost">
  spotId?: Prisma.StringFilter<"SpotCost"> | string
}

export type SpotCostCreateManySpotInput = {
  id?: string
  provider: $Enums.CostProvider
  service: $Enums.CostService
  costCents: number
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
}

export type SpotCostUpdateWithoutSpotInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  provider?: Prisma.EnumCostProviderFieldUpdateOperationsInput | $Enums.CostProvider
  service?: Prisma.EnumCostServiceFieldUpdateOperationsInput | $Enums.CostService
  costCents?: Prisma.IntFieldUpdateOperationsInput | number
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
}

export type SpotCostUncheckedUpdateWithoutSpotInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  provider?: Prisma.EnumCostProviderFieldUpdateOperationsInput | $Enums.CostProvider
  service?: Prisma.EnumCostServiceFieldUpdateOperationsInput | $Enums.CostService
  costCents?: Prisma.IntFieldUpdateOperationsInput | number
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
}

export type SpotCostUncheckedUpdateManyWithoutSpotInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  provider?: Prisma.EnumCostProviderFieldUpdateOperationsInput | $Enums.CostProvider
  service?: Prisma.EnumCostServiceFieldUpdateOperationsInput | $Enums.CostService
  costCents?: Prisma.IntFieldUpdateOperationsInput | number
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
}



export type SpotCostSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  provider?: boolean
  service?: boolean
  costCents?: boolean
  metadata?: boolean
  spotId?: boolean
  spot?: boolean | Prisma.SpotDefaultArgs<ExtArgs>
}, ExtArgs["result"]["spotCost"]>

export type SpotCostSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  provider?: boolean
  service?: boolean
  costCents?: boolean
  metadata?: boolean
  spotId?: boolean
  spot?: boolean | Prisma.SpotDefaultArgs<ExtArgs>
}, ExtArgs["result"]["spotCost"]>

export type SpotCostSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  provider?: boolean
  service?: boolean
  costCents?: boolean
  metadata?: boolean
  spotId?: boolean
  spot?: boolean | Prisma.SpotDefaultArgs<ExtArgs>
}, ExtArgs["result"]["spotCost"]>

export type SpotCostSelectScalar = {
  id?: boolean
  provider?: boolean
  service?: boolean
  costCents?: boolean
  metadata?: boolean
  spotId?: boolean
}

export type SpotCostOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "provider" | "service" | "costCents" | "metadata" | "spotId", ExtArgs["result"]["spotCost"]>
export type SpotCostInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  spot?: boolean | Prisma.SpotDefaultArgs<ExtArgs>
}
export type SpotCostIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  spot?: boolean | Prisma.SpotDefaultArgs<ExtArgs>
}
export type SpotCostIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  spot?: boolean | Prisma.SpotDefaultArgs<ExtArgs>
}

export type $SpotCostPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "SpotCost"
  objects: {
    spot: Prisma.$SpotPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    provider: $Enums.CostProvider
    service: $Enums.CostService
    costCents: number
    metadata: runtime.JsonValue | null
    spotId: string
  }, ExtArgs["result"]["spotCost"]>
  composites: {}
}

export type SpotCostGetPayload<S extends boolean | null | undefined | SpotCostDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$SpotCostPayload, S>

export type SpotCostCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<SpotCostFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: SpotCostCountAggregateInputType | true
  }

export interface SpotCostDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['SpotCost'], meta: { name: 'SpotCost' } }
  /**
   * Find zero or one SpotCost that matches the filter.
   * @param {SpotCostFindUniqueArgs} args - Arguments to find a SpotCost
   * @example
   * // Get one SpotCost
   * const spotCost = await prisma.spotCost.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends SpotCostFindUniqueArgs>(args: Prisma.SelectSubset<T, SpotCostFindUniqueArgs<ExtArgs>>): Prisma.Prisma__SpotCostClient<runtime.Types.Result.GetResult<Prisma.$SpotCostPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one SpotCost that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {SpotCostFindUniqueOrThrowArgs} args - Arguments to find a SpotCost
   * @example
   * // Get one SpotCost
   * const spotCost = await prisma.spotCost.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends SpotCostFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, SpotCostFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__SpotCostClient<runtime.Types.Result.GetResult<Prisma.$SpotCostPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first SpotCost that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SpotCostFindFirstArgs} args - Arguments to find a SpotCost
   * @example
   * // Get one SpotCost
   * const spotCost = await prisma.spotCost.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends SpotCostFindFirstArgs>(args?: Prisma.SelectSubset<T, SpotCostFindFirstArgs<ExtArgs>>): Prisma.Prisma__SpotCostClient<runtime.Types.Result.GetResult<Prisma.$SpotCostPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first SpotCost that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SpotCostFindFirstOrThrowArgs} args - Arguments to find a SpotCost
   * @example
   * // Get one SpotCost
   * const spotCost = await prisma.spotCost.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends SpotCostFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, SpotCostFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__SpotCostClient<runtime.Types.Result.GetResult<Prisma.$SpotCostPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more SpotCosts that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SpotCostFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all SpotCosts
   * const spotCosts = await prisma.spotCost.findMany()
   * 
   * // Get first 10 SpotCosts
   * const spotCosts = await prisma.spotCost.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const spotCostWithIdOnly = await prisma.spotCost.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends SpotCostFindManyArgs>(args?: Prisma.SelectSubset<T, SpotCostFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SpotCostPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a SpotCost.
   * @param {SpotCostCreateArgs} args - Arguments to create a SpotCost.
   * @example
   * // Create one SpotCost
   * const SpotCost = await prisma.spotCost.create({
   *   data: {
   *     // ... data to create a SpotCost
   *   }
   * })
   * 
   */
  create<T extends SpotCostCreateArgs>(args: Prisma.SelectSubset<T, SpotCostCreateArgs<ExtArgs>>): Prisma.Prisma__SpotCostClient<runtime.Types.Result.GetResult<Prisma.$SpotCostPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many SpotCosts.
   * @param {SpotCostCreateManyArgs} args - Arguments to create many SpotCosts.
   * @example
   * // Create many SpotCosts
   * const spotCost = await prisma.spotCost.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends SpotCostCreateManyArgs>(args?: Prisma.SelectSubset<T, SpotCostCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many SpotCosts and returns the data saved in the database.
   * @param {SpotCostCreateManyAndReturnArgs} args - Arguments to create many SpotCosts.
   * @example
   * // Create many SpotCosts
   * const spotCost = await prisma.spotCost.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many SpotCosts and only return the `id`
   * const spotCostWithIdOnly = await prisma.spotCost.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends SpotCostCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, SpotCostCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SpotCostPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a SpotCost.
   * @param {SpotCostDeleteArgs} args - Arguments to delete one SpotCost.
   * @example
   * // Delete one SpotCost
   * const SpotCost = await prisma.spotCost.delete({
   *   where: {
   *     // ... filter to delete one SpotCost
   *   }
   * })
   * 
   */
  delete<T extends SpotCostDeleteArgs>(args: Prisma.SelectSubset<T, SpotCostDeleteArgs<ExtArgs>>): Prisma.Prisma__SpotCostClient<runtime.Types.Result.GetResult<Prisma.$SpotCostPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one SpotCost.
   * @param {SpotCostUpdateArgs} args - Arguments to update one SpotCost.
   * @example
   * // Update one SpotCost
   * const spotCost = await prisma.spotCost.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends SpotCostUpdateArgs>(args: Prisma.SelectSubset<T, SpotCostUpdateArgs<ExtArgs>>): Prisma.Prisma__SpotCostClient<runtime.Types.Result.GetResult<Prisma.$SpotCostPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more SpotCosts.
   * @param {SpotCostDeleteManyArgs} args - Arguments to filter SpotCosts to delete.
   * @example
   * // Delete a few SpotCosts
   * const { count } = await prisma.spotCost.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends SpotCostDeleteManyArgs>(args?: Prisma.SelectSubset<T, SpotCostDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more SpotCosts.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SpotCostUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many SpotCosts
   * const spotCost = await prisma.spotCost.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends SpotCostUpdateManyArgs>(args: Prisma.SelectSubset<T, SpotCostUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more SpotCosts and returns the data updated in the database.
   * @param {SpotCostUpdateManyAndReturnArgs} args - Arguments to update many SpotCosts.
   * @example
   * // Update many SpotCosts
   * const spotCost = await prisma.spotCost.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more SpotCosts and only return the `id`
   * const spotCostWithIdOnly = await prisma.spotCost.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends SpotCostUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, SpotCostUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SpotCostPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one SpotCost.
   * @param {SpotCostUpsertArgs} args - Arguments to update or create a SpotCost.
   * @example
   * // Update or create a SpotCost
   * const spotCost = await prisma.spotCost.upsert({
   *   create: {
   *     // ... data to create a SpotCost
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the SpotCost we want to update
   *   }
   * })
   */
  upsert<T extends SpotCostUpsertArgs>(args: Prisma.SelectSubset<T, SpotCostUpsertArgs<ExtArgs>>): Prisma.Prisma__SpotCostClient<runtime.Types.Result.GetResult<Prisma.$SpotCostPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of SpotCosts.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SpotCostCountArgs} args - Arguments to filter SpotCosts to count.
   * @example
   * // Count the number of SpotCosts
   * const count = await prisma.spotCost.count({
   *   where: {
   *     // ... the filter for the SpotCosts we want to count
   *   }
   * })
  **/
  count<T extends SpotCostCountArgs>(
    args?: Prisma.Subset<T, SpotCostCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], SpotCostCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a SpotCost.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SpotCostAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends SpotCostAggregateArgs>(args: Prisma.Subset<T, SpotCostAggregateArgs>): Prisma.PrismaPromise<GetSpotCostAggregateType<T>>

  /**
   * Group by SpotCost.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SpotCostGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends SpotCostGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: SpotCostGroupByArgs['orderBy'] }
      : { orderBy?: SpotCostGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, SpotCostGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetSpotCostGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the SpotCost model
 */
readonly fields: SpotCostFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for SpotCost.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__SpotCostClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  spot<T extends Prisma.SpotDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.SpotDefaultArgs<ExtArgs>>): Prisma.Prisma__SpotClient<runtime.Types.Result.GetResult<Prisma.$SpotPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the SpotCost model
 */
export interface SpotCostFieldRefs {
  readonly id: Prisma.FieldRef<"SpotCost", 'String'>
  readonly provider: Prisma.FieldRef<"SpotCost", 'CostProvider'>
  readonly service: Prisma.FieldRef<"SpotCost", 'CostService'>
  readonly costCents: Prisma.FieldRef<"SpotCost", 'Int'>
  readonly metadata: Prisma.FieldRef<"SpotCost", 'Json'>
  readonly spotId: Prisma.FieldRef<"SpotCost", 'String'>
}
    

// Custom InputTypes
/**
 * SpotCost findUnique
 */
export type SpotCostFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SpotCost
   */
  select?: Prisma.SpotCostSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SpotCost
   */
  omit?: Prisma.SpotCostOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SpotCostInclude<ExtArgs> | null
  /**
   * Filter, which SpotCost to fetch.
   */
  where: Prisma.SpotCostWhereUniqueInput
}

/**
 * SpotCost findUniqueOrThrow
 */
export type SpotCostFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SpotCost
   */
  select?: Prisma.SpotCostSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SpotCost
   */
  omit?: Prisma.SpotCostOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SpotCostInclude<ExtArgs> | null
  /**
   * Filter, which SpotCost to fetch.
   */
  where: Prisma.SpotCostWhereUniqueInput
}

/**
 * SpotCost findFirst
 */
export type SpotCostFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SpotCost
   */
  select?: Prisma.SpotCostSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SpotCost
   */
  omit?: Prisma.SpotCostOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SpotCostInclude<ExtArgs> | null
  /**
   * Filter, which SpotCost to fetch.
   */
  where?: Prisma.SpotCostWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SpotCosts to fetch.
   */
  orderBy?: Prisma.SpotCostOrderByWithRelationInput | Prisma.SpotCostOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for SpotCosts.
   */
  cursor?: Prisma.SpotCostWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SpotCosts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SpotCosts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SpotCosts.
   */
  distinct?: Prisma.SpotCostScalarFieldEnum | Prisma.SpotCostScalarFieldEnum[]
}

/**
 * SpotCost findFirstOrThrow
 */
export type SpotCostFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SpotCost
   */
  select?: Prisma.SpotCostSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SpotCost
   */
  omit?: Prisma.SpotCostOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SpotCostInclude<ExtArgs> | null
  /**
   * Filter, which SpotCost to fetch.
   */
  where?: Prisma.SpotCostWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SpotCosts to fetch.
   */
  orderBy?: Prisma.SpotCostOrderByWithRelationInput | Prisma.SpotCostOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for SpotCosts.
   */
  cursor?: Prisma.SpotCostWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SpotCosts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SpotCosts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SpotCosts.
   */
  distinct?: Prisma.SpotCostScalarFieldEnum | Prisma.SpotCostScalarFieldEnum[]
}

/**
 * SpotCost findMany
 */
export type SpotCostFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SpotCost
   */
  select?: Prisma.SpotCostSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SpotCost
   */
  omit?: Prisma.SpotCostOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SpotCostInclude<ExtArgs> | null
  /**
   * Filter, which SpotCosts to fetch.
   */
  where?: Prisma.SpotCostWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SpotCosts to fetch.
   */
  orderBy?: Prisma.SpotCostOrderByWithRelationInput | Prisma.SpotCostOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing SpotCosts.
   */
  cursor?: Prisma.SpotCostWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SpotCosts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SpotCosts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SpotCosts.
   */
  distinct?: Prisma.SpotCostScalarFieldEnum | Prisma.SpotCostScalarFieldEnum[]
}

/**
 * SpotCost create
 */
export type SpotCostCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SpotCost
   */
  select?: Prisma.SpotCostSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SpotCost
   */
  omit?: Prisma.SpotCostOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SpotCostInclude<ExtArgs> | null
  /**
   * The data needed to create a SpotCost.
   */
  data: Prisma.XOR<Prisma.SpotCostCreateInput, Prisma.SpotCostUncheckedCreateInput>
}

/**
 * SpotCost createMany
 */
export type SpotCostCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many SpotCosts.
   */
  data: Prisma.SpotCostCreateManyInput | Prisma.SpotCostCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * SpotCost createManyAndReturn
 */
export type SpotCostCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SpotCost
   */
  select?: Prisma.SpotCostSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the SpotCost
   */
  omit?: Prisma.SpotCostOmit<ExtArgs> | null
  /**
   * The data used to create many SpotCosts.
   */
  data: Prisma.SpotCostCreateManyInput | Prisma.SpotCostCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SpotCostIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * SpotCost update
 */
export type SpotCostUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SpotCost
   */
  select?: Prisma.SpotCostSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SpotCost
   */
  omit?: Prisma.SpotCostOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SpotCostInclude<ExtArgs> | null
  /**
   * The data needed to update a SpotCost.
   */
  data: Prisma.XOR<Prisma.SpotCostUpdateInput, Prisma.SpotCostUncheckedUpdateInput>
  /**
   * Choose, which SpotCost to update.
   */
  where: Prisma.SpotCostWhereUniqueInput
}

/**
 * SpotCost updateMany
 */
export type SpotCostUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update SpotCosts.
   */
  data: Prisma.XOR<Prisma.SpotCostUpdateManyMutationInput, Prisma.SpotCostUncheckedUpdateManyInput>
  /**
   * Filter which SpotCosts to update
   */
  where?: Prisma.SpotCostWhereInput
  /**
   * Limit how many SpotCosts to update.
   */
  limit?: number
}

/**
 * SpotCost updateManyAndReturn
 */
export type SpotCostUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SpotCost
   */
  select?: Prisma.SpotCostSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the SpotCost
   */
  omit?: Prisma.SpotCostOmit<ExtArgs> | null
  /**
   * The data used to update SpotCosts.
   */
  data: Prisma.XOR<Prisma.SpotCostUpdateManyMutationInput, Prisma.SpotCostUncheckedUpdateManyInput>
  /**
   * Filter which SpotCosts to update
   */
  where?: Prisma.SpotCostWhereInput
  /**
   * Limit how many SpotCosts to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SpotCostIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * SpotCost upsert
 */
export type SpotCostUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SpotCost
   */
  select?: Prisma.SpotCostSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SpotCost
   */
  omit?: Prisma.SpotCostOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SpotCostInclude<ExtArgs> | null
  /**
   * The filter to search for the SpotCost to update in case it exists.
   */
  where: Prisma.SpotCostWhereUniqueInput
  /**
   * In case the SpotCost found by the `where` argument doesn't exist, create a new SpotCost with this data.
   */
  create: Prisma.XOR<Prisma.SpotCostCreateInput, Prisma.SpotCostUncheckedCreateInput>
  /**
   * In case the SpotCost was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.SpotCostUpdateInput, Prisma.SpotCostUncheckedUpdateInput>
}

/**
 * SpotCost delete
 */
export type SpotCostDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SpotCost
   */
  select?: Prisma.SpotCostSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SpotCost
   */
  omit?: Prisma.SpotCostOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SpotCostInclude<ExtArgs> | null
  /**
   * Filter which SpotCost to delete.
   */
  where: Prisma.SpotCostWhereUniqueInput
}

/**
 * SpotCost deleteMany
 */
export type SpotCostDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which SpotCosts to delete
   */
  where?: Prisma.SpotCostWhereInput
  /**
   * Limit how many SpotCosts to delete.
   */
  limit?: number
}

/**
 * SpotCost without action
 */
export type SpotCostDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SpotCost
   */
  select?: Prisma.SpotCostSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SpotCost
   */
  omit?: Prisma.SpotCostOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SpotCostInclude<ExtArgs> | null
}
