
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models.js'
export type * from './prismaNamespace.js'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  Brand: 'Brand',
  BrandAddress: 'BrandAddress',
  Spot: 'Spot',
  SpotInput: 'SpotInput',
  SpotCost: 'SpotCost',
  User: 'User',
  Workspace: 'Workspace',
  WorkspaceMember: 'WorkspaceMember'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const BrandScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  segment: 'segment',
  logoUrl: 'logoUrl',
  slogan: 'slogan',
  phoneNumber: 'phoneNumber',
  whatsapp: 'whatsapp',
  instagram: 'instagram',
  tiktok: 'tiktok',
  facebook: 'facebook',
  website: 'website',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  workspaceId: 'workspaceId'
} as const

export type BrandScalarFieldEnum = (typeof BrandScalarFieldEnum)[keyof typeof BrandScalarFieldEnum]


export const BrandAddressScalarFieldEnum = {
  id: 'id',
  state: 'state',
  city: 'city',
  neighborhood: 'neighborhood',
  street: 'street',
  number: 'number',
  complement: 'complement',
  brandId: 'brandId'
} as const

export type BrandAddressScalarFieldEnum = (typeof BrandAddressScalarFieldEnum)[keyof typeof BrandAddressScalarFieldEnum]


export const SpotScalarFieldEnum = {
  id: 'id',
  title: 'title',
  status: 'status',
  script: 'script',
  voiceId: 'voiceId',
  audioUrl: 'audioUrl',
  starred: 'starred',
  expectedDuration: 'expectedDuration',
  audioDuration: 'audioDuration',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  workspaceId: 'workspaceId',
  brandId: 'brandId',
  inputId: 'inputId'
} as const

export type SpotScalarFieldEnum = (typeof SpotScalarFieldEnum)[keyof typeof SpotScalarFieldEnum]


export const SpotInputScalarFieldEnum = {
  id: 'id',
  data: 'data',
  createdAt: 'createdAt',
  spotId: 'spotId'
} as const

export type SpotInputScalarFieldEnum = (typeof SpotInputScalarFieldEnum)[keyof typeof SpotInputScalarFieldEnum]


export const SpotCostScalarFieldEnum = {
  id: 'id',
  provider: 'provider',
  service: 'service',
  costCents: 'costCents',
  metadata: 'metadata',
  spotId: 'spotId'
} as const

export type SpotCostScalarFieldEnum = (typeof SpotCostScalarFieldEnum)[keyof typeof SpotCostScalarFieldEnum]


export const UserScalarFieldEnum = {
  id: 'id',
  name: 'name',
  email: 'email',
  password: 'password',
  avatarUrl: 'avatarUrl',
  authProvider: 'authProvider',
  authProviderId: 'authProviderId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type UserScalarFieldEnum = (typeof UserScalarFieldEnum)[keyof typeof UserScalarFieldEnum]


export const WorkspaceScalarFieldEnum = {
  id: 'id',
  name: 'name',
  type: 'type',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type WorkspaceScalarFieldEnum = (typeof WorkspaceScalarFieldEnum)[keyof typeof WorkspaceScalarFieldEnum]


export const WorkspaceMemberScalarFieldEnum = {
  role: 'role',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  workspaceId: 'workspaceId',
  userId: 'userId'
} as const

export type WorkspaceMemberScalarFieldEnum = (typeof WorkspaceMemberScalarFieldEnum)[keyof typeof WorkspaceMemberScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const JsonNullValueInput = {
  JsonNull: JsonNull
} as const

export type JsonNullValueInput = (typeof JsonNullValueInput)[keyof typeof JsonNullValueInput]


export const NullableJsonNullValueInput = {
  DbNull: DbNull,
  JsonNull: JsonNull
} as const

export type NullableJsonNullValueInput = (typeof NullableJsonNullValueInput)[keyof typeof NullableJsonNullValueInput]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]


export const JsonNullValueFilter = {
  DbNull: DbNull,
  JsonNull: JsonNull,
  AnyNull: AnyNull
} as const

export type JsonNullValueFilter = (typeof JsonNullValueFilter)[keyof typeof JsonNullValueFilter]

