export enum ErrorCodes {
  // Auth Errors
  AUTH_TOKEN_INVALID = "AUTH_TOKEN_INVALID",
  AUTH_TOKEN_EXPIRED = "AUTH_TOKEN_EXPIRED",
  AUTH_TOKEN_IS_MISSING = "AUTH_TOKEN_IS_MISSING",
  EMAIL_NOT_FOUND = "EMAIL_NOT_FOUND",
  PASSWORDS_DO_NOT_MATCH = "PASSWORDS_DO_NOT_MATCH",
  DISPOSABLE_EMAIL_NOT_ALLOWED = "DISPOSABLE_EMAIL_NOT_ALLOWED",
  EMAIL_ALREADY_IN_USE = "EMAIL_ALREADY_IN_USE",
  INVALID_GOOGLE_TOKEN = "INVALID_GOOGLE_TOKEN",
  GOOGLE_ACCOUNT_NOT_FOUND = "GOOGLE_ACCOUNT_NOT_FOUND",
  GOOGLE_ACCOUNT_INCOMPLETE = "GOOGLE_ACCOUNT_INCOMPLETE",
  EMAIL_ALREADY_REGISTERED_WITH_GOOGLE = "EMAIL_ALREADY_REGISTERED_WITH_GOOGLE",
  EMAIL_ALREADY_REGISTERED_WITH_PASSWORD = "EMAIL_ALREADY_REGISTERED_WITH_PASSWORD",
  ACCOUNT_CREATION_FAILED = "ACCOUNT_CREATION_FAILED",
  VERIFICATION_CODE_EXPIRED = "VERIFICATION_CODE_EXPIRED",
  VERIFICATION_CODE_INCORRECT = "VERIFICATION_CODE_INCORRECT",
  FINGERPRINT_LOCKED = "FINGERPRINT_LOCKED",
  USER_HAS_LOGIN_WITH_GOOGLE = "USER_HAS_LOGIN_WITH_GOOGLE",
  USER_HAS_LOGIN_WITH_EMAIL = "USER_HAS_LOGIN_WITH_EMAIL",
  USER_HAS_ONBOARDING_COMPLETED = "USER_HAS_ONBOARDING_COMPLETED",
  FORBIDDEN_ROLE = "FORBIDDEN_ROLE",
  MISSING_WORKSPACE_ID = "MISSING_WORKSPACE_ID",

  // Mail Error
  FAILED_TO_SEND_EMAIL = "FAILED_TO_SEND_EMAIL",

  // User errors
  USER_NOT_FOUND = "USER_NOT_FOUND",
  USER_ALREADY_IN_WORKSPACE = "USER_ALREADY_IN_WORKSPACE",
  USER_IN_OTHER_WORKSPACES = "USER_IN_OTHER_WORKSPACES",
  INVITE_EXPIRED = "INVITE_EXPIRED",
  INVITE_BELONGS_TO_ANOTHER_USER = "INVITE_BELONGS_TO_ANOTHER_USER",
  USER_DO_NOT_BELONGS_TO_WORKSPACE = "USER_DO_NOT_BELONGS_TO_WORKSPACE",
  OWNERS_USERS_CANNOT_BE_REMOVED = "OWNERS_USERS_CANNOT_BE_REMOVED",

  // Workspace
  WORKSPACE_NOT_FOUND = "WORKSPACE_NOT_FOUND",
  WORKSPACE_NAME_NOT_PROVIDED = "WORKSPACE_NAME_NOT_PROVIDED",
}
