
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser.js'
export { Prisma }
export * as $Enums from './enums.js'
export * from './enums.js';
/**
 * Model Brand
 * 
 */
export type Brand = Prisma.BrandModel
/**
 * Model BrandAddress
 * 
 */
export type BrandAddress = Prisma.BrandAddressModel
/**
 * Model BrandResponsible
 * 
 */
export type BrandResponsible = Prisma.BrandResponsibleModel
/**
 * Model Invite
 * 
 */
export type Invite = Prisma.InviteModel
/**
 * Model Notification
 * 
 */
export type Notification = Prisma.NotificationModel
/**
 * Model Plan
 * 
 */
export type Plan = Prisma.PlanModel
/**
 * Model Spot
 * 
 */
export type Spot = Prisma.SpotModel
/**
 * Model SpotInput
 * 
 */
export type SpotInput = Prisma.SpotInputModel
/**
 * Model SpotVersion
 * 
 */
export type SpotVersion = Prisma.SpotVersionModel
/**
 * Model SpotScript
 * 
 */
export type SpotScript = Prisma.SpotScriptModel
/**
 * Model SpotCost
 * 
 */
export type SpotCost = Prisma.SpotCostModel
/**
 * Model Subscription
 * 
 */
export type Subscription = Prisma.SubscriptionModel
/**
 * Model InvoiceSummary
 * 
 */
export type InvoiceSummary = Prisma.InvoiceSummaryModel
/**
 * Model Charge
 * 
 */
export type Charge = Prisma.ChargeModel
/**
 * Model User
 * 
 */
export type User = Prisma.UserModel
/**
 * Model Workspace
 * 
 */
export type Workspace = Prisma.WorkspaceModel
/**
 * Model WorkspaceMember
 * 
 */
export type WorkspaceMember = Prisma.WorkspaceMemberModel
