
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const AuthProvider = {
  GOOGLE: 'GOOGLE',
  EMAIL: 'EMAIL'
} as const

export type AuthProvider = (typeof AuthProvider)[keyof typeof AuthProvider]


export const BusinessSegment = {
  SUPERMARKET: 'SUPERMARKET',
  EVENTS: 'EVENTS',
  STORE: 'STORE',
  PHARMACY: 'PHARMACY',
  CLINIC: 'CLINIC',
  RESTAURANT: 'RESTAURANT',
  REAL_ESTATE: 'REAL_ESTATE',
  AUTOMOTIVE: 'AUTOMOTIVE',
  RADIO: 'RADIO',
  OTHER: 'OTHER'
} as const

export type BusinessSegment = (typeof BusinessSegment)[keyof typeof BusinessSegment]


export const BrazilianState = {
  AC: 'AC',
  AL: 'AL',
  AP: 'AP',
  AM: 'AM',
  BA: 'BA',
  CE: 'CE',
  DF: 'DF',
  ES: 'ES',
  GO: 'GO',
  MA: 'MA',
  MT: 'MT',
  MS: 'MS',
  MG: 'MG',
  PA: 'PA',
  PB: 'PB',
  PR: 'PR',
  PE: 'PE',
  PI: 'PI',
  RJ: 'RJ',
  RN: 'RN',
  RS: 'RS',
  RO: 'RO',
  RR: 'RR',
  SC: 'SC',
  SP: 'SP',
  SE: 'SE',
  TO: 'TO'
} as const

export type BrazilianState = (typeof BrazilianState)[keyof typeof BrazilianState]


export const InviteStatus = {
  PENDING: 'PENDING',
  ACCEPTED: 'ACCEPTED'
} as const

export type InviteStatus = (typeof InviteStatus)[keyof typeof InviteStatus]


export const SpotStatus = {
  DRAFT: 'DRAFT',
  PROCESSING: 'PROCESSING',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED'
} as const

export type SpotStatus = (typeof SpotStatus)[keyof typeof SpotStatus]


export const SpotTone = {
  ENERGETIC: 'ENERGETIC',
  URGENT: 'URGENT',
  PROFESSIONAL: 'PROFESSIONAL',
  EMOTIONAL: 'EMOTIONAL',
  CASUAL: 'CASUAL',
  PREMIUM: 'PREMIUM'
} as const

export type SpotTone = (typeof SpotTone)[keyof typeof SpotTone]


export const SpotType = {
  PROMOTION: 'PROMOTION',
  PRODUCT_LAUNCH: 'PRODUCT_LAUNCH',
  EVENT: 'EVENT',
  INSTITUTIONAL: 'INSTITUTIONAL',
  BRANDING: 'BRANDING',
  ANNOUNCEMENT: 'ANNOUNCEMENT',
  INVITATION: 'INVITATION',
  COMMEMORATIVE: 'COMMEMORATIVE',
  SEASONAL: 'SEASONAL',
  CLEARANCE_SALE: 'CLEARANCE_SALE',
  GRAND_OPENING: 'GRAND_OPENING',
  REOPENING: 'REOPENING',
  RECRUITMENT: 'RECRUITMENT',
  SERVICE_PROMOTION: 'SERVICE_PROMOTION',
  PUBLIC_NOTICE: 'PUBLIC_NOTICE',
  TESTIMONIAL: 'TESTIMONIAL'
} as const

export type SpotType = (typeof SpotType)[keyof typeof SpotType]


export const CostService = {
  LLM: 'LLM',
  TTS: 'TTS',
  STORAGE: 'STORAGE',
  MUSIC: 'MUSIC',
  PROCESSING: 'PROCESSING'
} as const

export type CostService = (typeof CostService)[keyof typeof CostService]


export const CostProvider = {
  ELEVEN_LABS: 'ELEVEN_LABS',
  OPEN_AI: 'OPEN_AI'
} as const

export type CostProvider = (typeof CostProvider)[keyof typeof CostProvider]


export const WorkspaceType = {
  INDIVIDUAL: 'INDIVIDUAL',
  COMPANY: 'COMPANY',
  AGENCY: 'AGENCY'
} as const

export type WorkspaceType = (typeof WorkspaceType)[keyof typeof WorkspaceType]


export const WorkspaceRole = {
  OWNER: 'OWNER',
  ADMIN: 'ADMIN',
  MEMBER: 'MEMBER'
} as const

export type WorkspaceRole = (typeof WorkspaceRole)[keyof typeof WorkspaceRole]
